export const aktuality = [
  {
    id: 1,
    Nazev: 'Česká televize navštívila Stromík',
    Text: '<p>Česká televize se v pořadu Události v regionech věnovala lesním školkám a 17.12.2019 navštívila náš lesní klub Stromík. Reportáž naleznete&nbsp;<a href="https://www.ceskatelevize.cz/ivysilani/10122427178-udalosti-v-regionech-brno/319281381991218-udalosti-v-regionech/obsah/739957-lesni-skolky-v-zime?fbclid=IwAR0YeCJerHKvBkt4FlWv5o-BJeqwZeFaWyX2JGqofSEPH-ukqGf2rhaSDE0">ZDE</a>.</p>',
    Datum: null,
    created_at: '2021-03-11T21:20:11.064Z',
    updated_at: '2021-03-11T21:20:11.082Z',
    Image: {
      id: 15,
      name: 'tv2.jpg',
      alternativeText: '',
      caption: '',
      width: 711,
      height: 398,
      formats: {
        small: {
          ext: '.jpg',
          url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1615497603/small_tv2_5823c3af5b.jpg',
          hash: 'small_tv2_5823c3af5b',
          mime: 'image/jpeg',
          name: 'small_tv2.jpg',
          path: null,
          size: 49.23,
          width: 500,
          height: 280,
          provider_metadata: {
            public_id: 'small_tv2_5823c3af5b',
            resource_type: 'image',
          },
        },
        thumbnail: {
          ext: '.jpg',
          url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1615497602/thumbnail_tv2_5823c3af5b.jpg',
          hash: 'thumbnail_tv2_5823c3af5b',
          mime: 'image/jpeg',
          name: 'thumbnail_tv2.jpg',
          path: null,
          size: 13.61,
          width: 245,
          height: 137,
          provider_metadata: {
            public_id: 'thumbnail_tv2_5823c3af5b',
            resource_type: 'image',
          },
        },
      },
      hash: 'tv2_5823c3af5b',
      ext: '.jpg',
      mime: 'image/jpeg',
      size: 98.61,
      url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1615497601/tv2_5823c3af5b.jpg',
      previewUrl: null,
      provider: 'cloudinary',
      provider_metadata: {
        public_id: 'tv2_5823c3af5b',
        resource_type: 'image',
      },
      created_at: '2021-03-11T21:20:03.799Z',
      updated_at: '2021-03-11T21:20:03.824Z',
    },
  },
  {
    id: 2,
    Nazev: 'PF 2020',
    Text: '<p>Všechno nejlepší do roku 2020!</p>',
    Datum: null,
    created_at: '2021-03-11T21:21:33.498Z',
    updated_at: '2021-03-11T21:21:33.513Z',
    Image: {
      id: 16,
      name: 'pf2020.png',
      alternativeText: '',
      caption: '',
      width: 800,
      height: 348,
      formats: {
        small: {
          ext: '.png',
          url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1615497690/small_pf2020_1d104b0c00.png',
          hash: 'small_pf2020_1d104b0c00',
          mime: 'image/png',
          name: 'small_pf2020.png',
          path: null,
          size: 39.04,
          width: 500,
          height: 218,
          provider_metadata: {
            public_id: 'small_pf2020_1d104b0c00',
            resource_type: 'image',
          },
        },
        medium: {
          ext: '.png',
          url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1615497689/medium_pf2020_1d104b0c00.png',
          hash: 'medium_pf2020_1d104b0c00',
          mime: 'image/png',
          name: 'medium_pf2020.png',
          path: null,
          size: 78.64,
          width: 750,
          height: 326,
          provider_metadata: {
            public_id: 'medium_pf2020_1d104b0c00',
            resource_type: 'image',
          },
        },
        thumbnail: {
          ext: '.png',
          url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1615497688/thumbnail_pf2020_1d104b0c00.png',
          hash: 'thumbnail_pf2020_1d104b0c00',
          mime: 'image/png',
          name: 'thumbnail_pf2020.png',
          path: null,
          size: 12.61,
          width: 245,
          height: 107,
          provider_metadata: {
            public_id: 'thumbnail_pf2020_1d104b0c00',
            resource_type: 'image',
          },
        },
      },
      hash: 'pf2020_1d104b0c00',
      ext: '.png',
      mime: 'image/png',
      size: 76.66,
      url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1615497687/pf2020_1d104b0c00.png',
      previewUrl: null,
      provider: 'cloudinary',
      provider_metadata: {
        public_id: 'pf2020_1d104b0c00',
        resource_type: 'image',
      },
      created_at: '2021-03-11T21:21:30.412Z',
      updated_at: '2021-03-11T21:21:30.427Z',
    },
  },
  {
    id: 3,
    Nazev: 'Keramika pro dospělé',
    Text: '<p>Zveme vás na keramiku s Vítkem Třískou pro dospělé.</p>',
    Datum: null,
    created_at: '2021-03-11T21:22:25.254Z',
    updated_at: '2021-03-11T21:22:25.266Z',
    Image: {
      id: 17,
      name: 'plakat-keramika-leden-2020.png',
      alternativeText: '',
      caption: '',
      width: 565,
      height: 800,
      formats: {
        small: {
          ext: '.png',
          url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1615497740/small_plakat_keramika_leden_2020_75283d2e3a.png',
          hash: 'small_plakat_keramika_leden_2020_75283d2e3a',
          mime: 'image/png',
          name: 'small_plakat-keramika-leden-2020.png',
          path: null,
          size: 223.84,
          width: 353,
          height: 500,
          provider_metadata: {
            public_id: 'small_plakat_keramika_leden_2020_75283d2e3a',
            resource_type: 'image',
          },
        },
        medium: {
          ext: '.png',
          url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1615497739/medium_plakat_keramika_leden_2020_75283d2e3a.png',
          hash: 'medium_plakat_keramika_leden_2020_75283d2e3a',
          mime: 'image/png',
          name: 'medium_plakat-keramika-leden-2020.png',
          path: null,
          size: 466.25,
          width: 530,
          height: 750,
          provider_metadata: {
            public_id: 'medium_plakat_keramika_leden_2020_75283d2e3a',
            resource_type: 'image',
          },
        },
        thumbnail: {
          ext: '.png',
          url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1615497737/thumbnail_plakat_keramika_leden_2020_75283d2e3a.png',
          hash: 'thumbnail_plakat_keramika_leden_2020_75283d2e3a',
          mime: 'image/png',
          name: 'thumbnail_plakat-keramika-leden-2020.png',
          path: null,
          size: 26.36,
          width: 110,
          height: 156,
          provider_metadata: {
            public_id: 'thumbnail_plakat_keramika_leden_2020_75283d2e3a',
            resource_type: 'image',
          },
        },
      },
      hash: 'plakat_keramika_leden_2020_75283d2e3a',
      ext: '.png',
      mime: 'image/png',
      size: 481.18,
      url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1615497736/plakat_keramika_leden_2020_75283d2e3a.png',
      previewUrl: null,
      provider: 'cloudinary',
      provider_metadata: {
        public_id: 'plakat_keramika_leden_2020_75283d2e3a',
        resource_type: 'image',
      },
      created_at: '2021-03-11T21:22:21.032Z',
      updated_at: '2021-03-11T21:22:21.045Z',
    },
  },
  {
    id: 4,
    Nazev: 'Masopustní průvod Pozořice  ',
    Text: '<p>Zveme vás na tradiční Masopustní průvod v Pozořicích</p>',
    Datum: null,
    created_at: '2021-03-11T21:23:21.948Z',
    updated_at: '2021-03-11T21:23:21.964Z',
    Image: {
      id: 18,
      name: 'masopust2020.jpg',
      alternativeText: '',
      caption: '',
      width: 799,
      height: 562,
      formats: {
        small: {
          ext: '.jpg',
          url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1615497799/small_masopust2020_51c5748f97.jpg',
          hash: 'small_masopust2020_51c5748f97',
          mime: 'image/jpeg',
          name: 'small_masopust2020.jpg',
          path: null,
          size: 47.9,
          width: 500,
          height: 352,
          provider_metadata: {
            public_id: 'small_masopust2020_51c5748f97',
            resource_type: 'image',
          },
        },
        medium: {
          ext: '.jpg',
          url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1615497798/medium_masopust2020_51c5748f97.jpg',
          hash: 'medium_masopust2020_51c5748f97',
          mime: 'image/jpeg',
          name: 'medium_masopust2020.jpg',
          path: null,
          size: 99.07,
          width: 750,
          height: 528,
          provider_metadata: {
            public_id: 'medium_masopust2020_51c5748f97',
            resource_type: 'image',
          },
        },
        thumbnail: {
          ext: '.jpg',
          url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1615497797/thumbnail_masopust2020_51c5748f97.jpg',
          hash: 'thumbnail_masopust2020_51c5748f97',
          mime: 'image/jpeg',
          name: 'thumbnail_masopust2020.jpg',
          path: null,
          size: 11.53,
          width: 222,
          height: 156,
          provider_metadata: {
            public_id: 'thumbnail_masopust2020_51c5748f97',
            resource_type: 'image',
          },
        },
      },
      hash: 'masopust2020_51c5748f97',
      ext: '.jpg',
      mime: 'image/jpeg',
      size: 115.31,
      url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1615497797/masopust2020_51c5748f97.jpg',
      previewUrl: null,
      provider: 'cloudinary',
      provider_metadata: {
        public_id: 'masopust2020_51c5748f97',
        resource_type: 'image',
      },
      created_at: '2021-03-11T21:23:19.928Z',
      updated_at: '2021-03-11T21:23:19.943Z',
    },
  },
  {
    id: 25,
    Nazev: 'Zápis na školní rok 2022/23',
    Text: '<p><strong>LMŠ Stromík otevírá své brány novým dětem!</strong></p><p>Učit se, hrát si, objevovat, připravovat se do školy, to vše můžeme dělat v tom nejkrásnějším prostředí, v přírodě.&nbsp;</p><p>Zápis proběhne <strong>12. května 14 – 16 h</strong>.</p><p>Podrobné informace k zápisu si můžete přečíst <a href="https://stromik.cz/info/zapis">zde</a>.</p><p>Srdečně zveme všechny zájemce na Den otevřených vrátek 20. dubna od 14 do 16 h na naší zahradě.</p><p>Těšíme se na vás i vaše děti!</p><p>&nbsp;</p>',
    Datum: null,
    created_at: '2022-03-14T15:57:57.087Z',
    updated_at: '2022-03-14T15:57:57.098Z',
    Image: null,
  },
  {
    id: 6,
    Nazev: 'Zápis na školní rok 2020/2021',
    Text: '<p><strong>Stromík otevírá své brány novým dětem!!</strong>&nbsp;Učit se, hrát si, objevovat, připravovat se do školy, to vše můžeme dělat v tom nejkrásnějším prostředí, v přírodě. Chcete se k nám přidat? Zápis probíhá od <strong>20.4. - 16.5.&nbsp;</strong></p><p>Postup podání přihlášky:</p><p>1.Vyplňte následující<strong>&nbsp;</strong><a href="https://docs.google.com/forms/d/e/1FAIpQLScahiOxN8mckaOxlJq3p_IyKosV6YGoG5z57La7AB5M9XgOnw/viewform?usp=sf_link"><strong>formulář</strong></a>&nbsp;žádosti o zápis do DLK Stromík&nbsp;</p><p>2.Stáhněte si dokument&nbsp;<a href="https://drive.google.com/file/d/1PaOMQF1etS5MKPuhMIJZC7nxiZAVOUVe/view"><strong>žádost o přijetí</strong></a><strong>&nbsp;</strong>a&nbsp;<a href="https://drive.google.com/file/d/13B561J5RXJdIkTsE1wsS3ZaWNQNl8Dfh/view"><strong>zdravotní dotazník</strong></a></p><p>3. Oba vyplněné formuláře doručte v&nbsp;termínu do 16.5.&nbsp;&nbsp;</p><p>- Poštou na adresu Hostěnická 626, Pozořice, 664 07</p><p>- Osobně 11.5. 2020 na zahradě DLK Stromík v Pozořicích od 14 do 16 hodin&nbsp;</p><p>Do 1.6. dostanete rozhodnutí o přijetí&nbsp;</p><p><strong>Ptejte se na vše, co byste rádi věděli</strong> stromik@stromik.cz 776859293 (koordinátroka)&nbsp;</p>',
    Datum: null,
    created_at: '2021-03-11T21:24:43.832Z',
    updated_at: '2021-03-11T21:24:43.844Z',
    Image: {
      id: 19,
      name: '914ebabc-78e2-42bd-916f-64abaed1b1fc.jpg',
      alternativeText: '',
      caption: '',
      width: 600,
      height: 800,
      formats: {
        small: {
          ext: '.jpg',
          url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1615497875/small_914ebabc_78e2_42bd_916f_64abaed1b1fc_392995eb4c.jpg',
          hash: 'small_914ebabc_78e2_42bd_916f_64abaed1b1fc_392995eb4c',
          mime: 'image/jpeg',
          name: 'small_914ebabc-78e2-42bd-916f-64abaed1b1fc.jpg',
          path: null,
          size: 48.62,
          width: 375,
          height: 500,
          provider_metadata: {
            public_id: 'small_914ebabc_78e2_42bd_916f_64abaed1b1fc_392995eb4c',
            resource_type: 'image',
          },
        },
        medium: {
          ext: '.jpg',
          url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1615497874/medium_914ebabc_78e2_42bd_916f_64abaed1b1fc_392995eb4c.jpg',
          hash: 'medium_914ebabc_78e2_42bd_916f_64abaed1b1fc_392995eb4c',
          mime: 'image/jpeg',
          name: 'medium_914ebabc-78e2-42bd-916f-64abaed1b1fc.jpg',
          path: null,
          size: 104.78,
          width: 563,
          height: 750,
          provider_metadata: {
            public_id: 'medium_914ebabc_78e2_42bd_916f_64abaed1b1fc_392995eb4c',
            resource_type: 'image',
          },
        },
        thumbnail: {
          ext: '.jpg',
          url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1615497873/thumbnail_914ebabc_78e2_42bd_916f_64abaed1b1fc_392995eb4c.jpg',
          hash: 'thumbnail_914ebabc_78e2_42bd_916f_64abaed1b1fc_392995eb4c',
          mime: 'image/jpeg',
          name: 'thumbnail_914ebabc-78e2-42bd-916f-64abaed1b1fc.jpg',
          path: null,
          size: 6.36,
          width: 117,
          height: 156,
          provider_metadata: {
            public_id:
              'thumbnail_914ebabc_78e2_42bd_916f_64abaed1b1fc_392995eb4c',
            resource_type: 'image',
          },
        },
      },
      hash: '914ebabc_78e2_42bd_916f_64abaed1b1fc_392995eb4c',
      ext: '.jpg',
      mime: 'image/jpeg',
      size: 122.03,
      url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1615497872/914ebabc_78e2_42bd_916f_64abaed1b1fc_392995eb4c.jpg',
      previewUrl: null,
      provider: 'cloudinary',
      provider_metadata: {
        public_id: '914ebabc_78e2_42bd_916f_64abaed1b1fc_392995eb4c',
        resource_type: 'image',
      },
      created_at: '2021-03-11T21:24:35.801Z',
      updated_at: '2021-03-11T21:24:35.813Z',
    },
  },
  {
    id: 8,
    Nazev: 'Podzimní Výletníček ',
    Text: '<p>Pojďte si prožít dobrodružství podzimního lesa. Podzimní kroužek Výletníček pro rodiče s dětma se blíží.&nbsp;</p><p>Kdy:&nbsp; ve středy 23.9, 30.9., 7.10., 14.10. ,21.10. ,4.11., 11.11., 18.11.</p><p>v čase: 9:30 - 11:30</p><p>na zahradě DLK Stromík&nbsp;</p><p>přihlašovat se můžete&nbsp;<a href="https://docs.google.com/forms/d/e/1FAIpQLSdk3JAGkUuDfvo-h3gFi9-49D6UktjbHCXdNCzKjWUll1boew/viewform?fbclid=IwAR3WSCcPaM8hv839vRbpGpCc7-8Hkt8nuoCFBOBcAesSxJZfT-HqRcSj64A">zde</a></p>',
    Datum: null,
    created_at: '2021-03-11T21:26:30.242Z',
    updated_at: '2021-03-11T21:26:30.258Z',
    Image: {
      id: 20,
      name: 'výletníček-(1).jpg',
      alternativeText: '',
      caption: '',
      width: 565,
      height: 800,
      formats: {
        small: {
          ext: '.jpg',
          url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1615497932/small_vyletnicek_1_bafb501afb.jpg',
          hash: 'small_vyletnicek_1_bafb501afb',
          mime: 'image/jpeg',
          name: 'small_výletníček-(1).jpg',
          path: null,
          size: 53.28,
          width: 353,
          height: 500,
          provider_metadata: {
            public_id: 'small_vyletnicek_1_bafb501afb',
            resource_type: 'image',
          },
        },
        medium: {
          ext: '.jpg',
          url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1615497931/medium_vyletnicek_1_bafb501afb.jpg',
          hash: 'medium_vyletnicek_1_bafb501afb',
          mime: 'image/jpeg',
          name: 'medium_výletníček-(1).jpg',
          path: null,
          size: 110.38,
          width: 530,
          height: 750,
          provider_metadata: {
            public_id: 'medium_vyletnicek_1_bafb501afb',
            resource_type: 'image',
          },
        },
        thumbnail: {
          ext: '.jpg',
          url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1615497929/thumbnail_vyletnicek_1_bafb501afb.jpg',
          hash: 'thumbnail_vyletnicek_1_bafb501afb',
          mime: 'image/jpeg',
          name: 'thumbnail_výletníček-(1).jpg',
          path: null,
          size: 6.05,
          width: 110,
          height: 156,
          provider_metadata: {
            public_id: 'thumbnail_vyletnicek_1_bafb501afb',
            resource_type: 'image',
          },
        },
      },
      hash: 'vyletnicek_1_bafb501afb',
      ext: '.jpg',
      mime: 'image/jpeg',
      size: 128.15,
      url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1615497928/vyletnicek_1_bafb501afb.jpg',
      previewUrl: null,
      provider: 'cloudinary',
      provider_metadata: {
        public_id: 'vyletnicek_1_bafb501afb',
        resource_type: 'image',
      },
      created_at: '2021-03-11T21:25:33.483Z',
      updated_at: '2021-03-11T21:25:33.497Z',
    },
  },
  {
    id: 5,
    Nazev: 'Uzavření DLK Stromík',
    Text: '<p>UZAVÍRÁME DO ODVOLÁNÍ DLK Stromík.</p><p>Na základě preventivních opatření vlády ČR a nařízení Rady města Brna č. 5/2020 uzavíráme do odvolání provoz DLK Stromík s&nbsp;platností od 17.3.2020. Podporujeme a přidáváme se takto k&nbsp;preventivním krokům a snaze omezit kontakt mezi lidmi ve větší skupině navzájem. Nikdo z nás by si v budoucnu určitě neodpustil, kdybychom přispěli k nakažení kohokoliv z Vás nebo Vašich blízkých.</p><p>Přejeme Vám hodně sil a pevné zdraví!</p>',
    Datum: null,
    created_at: '2021-03-11T21:23:55.070Z',
    updated_at: '2021-03-11T21:54:48.915Z',
    Image: null,
  },
  {
    id: 7,
    Nazev: 'Letní tábory ve Stromíku i Mariánce',
    Text: '<p>Stromík a Mariánka vás zvou na letní příměstské tábory!</p>',
    Datum: null,
    created_at: '2021-03-11T21:25:36.137Z',
    updated_at: '2021-03-11T21:27:51.746Z',
    Image: {
      id: 21,
      name: 'tabory.jpg',
      alternativeText: '',
      caption: '',
      width: 504,
      height: 800,
      formats: {
        small: {
          ext: '.jpg',
          url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1615498069/small_tabory_bdfe5fa944.jpg',
          hash: 'small_tabory_bdfe5fa944',
          mime: 'image/jpeg',
          name: 'small_tabory.jpg',
          path: null,
          size: 32.72,
          width: 315,
          height: 500,
          provider_metadata: {
            public_id: 'small_tabory_bdfe5fa944',
            resource_type: 'image',
          },
        },
        medium: {
          ext: '.jpg',
          url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1615498068/medium_tabory_bdfe5fa944.jpg',
          hash: 'medium_tabory_bdfe5fa944',
          mime: 'image/jpeg',
          name: 'medium_tabory.jpg',
          path: null,
          size: 60.65,
          width: 473,
          height: 750,
          provider_metadata: {
            public_id: 'medium_tabory_bdfe5fa944',
            resource_type: 'image',
          },
        },
        thumbnail: {
          ext: '.jpg',
          url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1615498067/thumbnail_tabory_bdfe5fa944.jpg',
          hash: 'thumbnail_tabory_bdfe5fa944',
          mime: 'image/jpeg',
          name: 'thumbnail_tabory.jpg',
          path: null,
          size: 4.24,
          width: 98,
          height: 156,
          provider_metadata: {
            public_id: 'thumbnail_tabory_bdfe5fa944',
            resource_type: 'image',
          },
        },
      },
      hash: 'tabory_bdfe5fa944',
      ext: '.jpg',
      mime: 'image/jpeg',
      size: 68.58,
      url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1615498066/tabory_bdfe5fa944.jpg',
      previewUrl: null,
      provider: 'cloudinary',
      provider_metadata: {
        public_id: 'tabory_bdfe5fa944',
        resource_type: 'image',
      },
      created_at: '2021-03-11T21:27:49.274Z',
      updated_at: '2021-03-11T21:27:49.286Z',
    },
  },
  {
    id: 26,
    Nazev: 'Výletníček jaro 2022',
    Text: '<p>Srdečně zveme na jarní cyklus Výletníčku!</p><p>Setkávat se budeme na zahradě hájenky opět ve<strong> čtvrtky od 9:30 do 11:30 h</strong>.</p><p>Termíny: 7. 4., 14. 4., 21. 4., 28. 4., 5. 5., 12. 5., 19. 5., 26. 5.</p><p>Přihlašovat se můžete <a href="https://docs.google.com/forms/d/e/1FAIpQLSe6P9m1Kbqp9WaMtZEQB5luV051Lg2JDcAdaMa7BL600oO4_Q/viewform?usp=sf_link">zde</a>.</p><p><i>Aktualizace 28. 3. - kapacita je v tuto chvíli naplněna, můžete se přihlašovat a ozveme se vám v případě absence některého z účastníků.</i></p>',
    Datum: null,
    created_at: '2022-03-28T10:28:12.604Z',
    updated_at: '2022-03-28T10:28:12.613Z',
    Image: null,
  },
  {
    id: 27,
    Nazev: 'Rodinné divadelní odpoledne 2022',
    Text: '<p>V sobotu, 21.května odpoledne zveme domácí i přespolní, tety, strýce, babičky, dědečky i sousedy, blízké i vzdálené, zkrátka všechny, kteří si chtějí užít odpoledne plné hudby 🎹 zpěvu 🎤 divadla 🎭 radosti 🤩 samozřejmě výborného jídla a pití 🥓🌭🍻🍷!<br>Tombola a cimbál jako bonus 🏵</p><p>&nbsp;</p>',
    Datum: null,
    created_at: '2022-05-19T07:08:35.065Z',
    updated_at: '2022-05-19T07:08:35.076Z',
    Image: {
      id: 29,
      name: 'rdo2022.jpg',
      alternativeText: '',
      caption: '',
      width: 509,
      height: 720,
      formats: {
        small: {
          ext: '.jpg',
          url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1652944106/small_rdo2022_874cb79de0.jpg',
          hash: 'small_rdo2022_874cb79de0',
          mime: 'image/jpeg',
          name: 'small_rdo2022.jpg',
          path: null,
          size: 43.66,
          width: 353,
          height: 500,
          provider_metadata: {
            public_id: 'small_rdo2022_874cb79de0',
            resource_type: 'image',
          },
        },
        thumbnail: {
          ext: '.jpg',
          url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1652944105/thumbnail_rdo2022_874cb79de0.jpg',
          hash: 'thumbnail_rdo2022_874cb79de0',
          mime: 'image/jpeg',
          name: 'thumbnail_rdo2022.jpg',
          path: null,
          size: 5.09,
          width: 110,
          height: 156,
          provider_metadata: {
            public_id: 'thumbnail_rdo2022_874cb79de0',
            resource_type: 'image',
          },
        },
      },
      hash: 'rdo2022_874cb79de0',
      ext: '.jpg',
      mime: 'image/jpeg',
      size: 79.61,
      url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1652944105/rdo2022_874cb79de0.jpg',
      previewUrl: null,
      provider: 'cloudinary',
      provider_metadata: {
        public_id: 'rdo2022_874cb79de0',
        resource_type: 'image',
      },
      created_at: '2022-05-19T07:08:26.854Z',
      updated_at: '2022-05-19T07:08:26.866Z',
    },
  },
  {
    id: 19,
    Nazev: 'Hledáme průvodce!',
    Text: '<p>Chceš dětem pomáhat objevovat svět?</p><p>Hledáme průvodce a lektory environmentálních programů!</p><p>nabízíme:</p><ul><li>skvělý tým a prostředí</li><li>práci v přírodě</li><li>příležitosti k dalšímu vzdělávání</li><li>úvazek dle tvých možností</li><li>jistotu v nejisté době</li></ul><p>co potřebujeme:</p><ul><li>zkušenosti s pedagogikou dětí předškolního nebo mladšího školního věku</li><li>nevadí ti být venku za každého počasí</li><li>umíš spolupracovat v týmu</li><li>jsi flexibilní a rád přijímáš nové výzvy</li></ul><p>co se hodí:</p><ul><li>umíš hrát na hudební nástroje, zpíváš, hraješ divadlo či tvoříš</li><li>jsi nadšený milovník přírody, poznáš stopy ve sněhu, ptáky na stromech…</li></ul><p>Jestli se ti tohle všechno líbí, pošli nám životopis a krátký motivační dopis na <strong>info@stromik.cz</strong>.</p>',
    Datum: null,
    created_at: '2022-01-20T08:17:00.156Z',
    updated_at: '2022-01-24T11:22:14.757Z',
    Image: null,
  },
  {
    id: 15,
    Nazev: 'Podzimní Výletníček',
    Text: '<p>Srdečně zveme všechny mužíčky a žínky s doprovodem dospěláků do Výletníčku.</p><p>Začínáme na hájence 30. září!</p><p>Přihlašovat se můžete <a href="https://docs.google.com/forms/d/e/1FAIpQLSe6P9m1Kbqp9WaMtZEQB5luV051Lg2JDcAdaMa7BL600oO4_Q/viewform">zde</a>.</p>',
    Datum: null,
    created_at: '2021-09-08T14:54:36.668Z',
    updated_at: '2021-09-08T14:54:36.682Z',
    Image: {
      id: 25,
      name: 'Vyl_podzim_2021.jpg',
      alternativeText: '',
      caption: '',
      width: 4960,
      height: 7016,
      formats: {
        large: {
          ext: '.jpg',
          url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1631112869/large_Vyl_podzim_2021_2157adfc83.jpg',
          hash: 'large_Vyl_podzim_2021_2157adfc83',
          mime: 'image/jpeg',
          name: 'large_Vyl_podzim_2021.jpg',
          path: null,
          size: 156.38,
          width: 707,
          height: 1000,
          provider_metadata: {
            public_id: 'large_Vyl_podzim_2021_2157adfc83',
            resource_type: 'image',
          },
        },
        small: {
          ext: '.jpg',
          url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1631112872/small_Vyl_podzim_2021_2157adfc83.jpg',
          hash: 'small_Vyl_podzim_2021_2157adfc83',
          mime: 'image/jpeg',
          name: 'small_Vyl_podzim_2021.jpg',
          path: null,
          size: 46.69,
          width: 353,
          height: 500,
          provider_metadata: {
            public_id: 'small_Vyl_podzim_2021_2157adfc83',
            resource_type: 'image',
          },
        },
        medium: {
          ext: '.jpg',
          url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1631112870/medium_Vyl_podzim_2021_2157adfc83.jpg',
          hash: 'medium_Vyl_podzim_2021_2157adfc83',
          mime: 'image/jpeg',
          name: 'medium_Vyl_podzim_2021.jpg',
          path: null,
          size: 91.92,
          width: 530,
          height: 750,
          provider_metadata: {
            public_id: 'medium_Vyl_podzim_2021_2157adfc83',
            resource_type: 'image',
          },
        },
        thumbnail: {
          ext: '.jpg',
          url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1631112868/thumbnail_Vyl_podzim_2021_2157adfc83.jpg',
          hash: 'thumbnail_Vyl_podzim_2021_2157adfc83',
          mime: 'image/jpeg',
          name: 'thumbnail_Vyl_podzim_2021.jpg',
          path: null,
          size: 5.73,
          width: 110,
          height: 156,
          provider_metadata: {
            public_id: 'thumbnail_Vyl_podzim_2021_2157adfc83',
            resource_type: 'image',
          },
        },
      },
      hash: 'Vyl_podzim_2021_2157adfc83',
      ext: '.jpg',
      mime: 'image/jpeg',
      size: 3500.18,
      url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1631112867/Vyl_podzim_2021_2157adfc83.jpg',
      previewUrl: null,
      provider: 'cloudinary',
      provider_metadata: {
        public_id: 'Vyl_podzim_2021_2157adfc83',
        resource_type: 'image',
      },
      created_at: '2021-09-08T14:54:32.359Z',
      updated_at: '2021-09-08T14:54:32.383Z',
    },
  },
  {
    id: 17,
    Nazev: 'Výletníček - zima 2022',
    Text: '<p>Pro velký zájem otevíráme i zimní cyklus oblíbeného kroužku! Setkávat se budeme opět ve čtvrtky dopoledne od 20. 1. – 24. 2. na naší zahradě.</p><p>Přihlašovat se můžete <a href="https://docs.google.com/forms/d/e/1FAIpQLSe6P9m1Kbqp9WaMtZEQB5luV051Lg2JDcAdaMa7BL600oO4_Q/viewform">zde</a>.</p>',
    Datum: null,
    created_at: '2021-12-20T08:05:22.567Z',
    updated_at: '2021-12-20T08:05:50.074Z',
    Image: null,
  },
  {
    id: 10,
    Nazev: 'TÁBORY 2021',
    Text: '<p>V letošním roce se opět můžete těšit na příměstské tábory ve Stromíku v Pozořicích, nebo v Mariánce v Líšni.&nbsp;</p><p>Podrobné informace k letošním táborům najdete&nbsp;<a href="https://www.lesnikavyl.cz/files/tabory_2021_anotace.pdf"><strong>zde</strong></a>.</p><p>Přihlašovat se můžete online –&nbsp;<a href="https://docs.google.com/forms/d/e/1FAIpQLSfcZZDo1NSlXCrQ6HfZwXHuLV9p3xkmT7a9jrfmf4n564FzrA/viewform?usp=sf_link"><strong>PŘIHLÁŠKA</strong></a>.&nbsp;</p><p>Můžete vybírat&nbsp;</p><p>12. – 16. 7.: &nbsp;</p><p>Mariánka:&nbsp;<i>S pohádkou v lese</i>&nbsp;– předškolní děti 3–7 let</p><p>Stromík:&nbsp;<i>Po stopách rudého bizona –</i>&nbsp;předškolní děti 3–7 let</p><p>19. – 23. 7.:</p><p>Mariánka:&nbsp;<i>Malý stopař –</i>&nbsp;předškolní děti 3–7 let</p><p>Mariánka:&nbsp;<i>Lesní olympiáda –&nbsp;</i>školní děti 7–11 let</p><p>Stromík:&nbsp;<i>Zázraky přírody –</i>&nbsp;děti ve věku 5–8 let</p><p>26. – 30. 7.:&nbsp;</p><p>Stromík:&nbsp;<i>Hurá do lesa –</i>&nbsp;předškolní děti 3–7 let</p><p>Stromík:&nbsp;<i>Hurá do lesa –&nbsp;</i>školní děti 7–11 let</p><p>16. – 20. 8.:&nbsp;</p><p>Stromík:&nbsp;<i>Kdo tam bydlí?&nbsp;</i>– předškolní děti 3–7 let</p><p>Stromík:&nbsp;<i>Kdo tam bydlí?&nbsp;</i>– školní děti 7–11 let</p><p>Cena tábora je 1 900 Kč.</p><p>Těšíme se na vaše děti a věříme, že si konečně léto užijí venku a se spoustou kamarádů!</p>',
    Datum: null,
    created_at: '2021-03-11T21:29:37.031Z',
    updated_at: '2021-03-11T21:56:15.981Z',
    Image: {
      id: 23,
      name: 'tábory-2021-page-001.jpg',
      alternativeText: '',
      caption: '',
      width: 565,
      height: 800,
      formats: {
        small: {
          ext: '.jpg',
          url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1615498174/small_tabory_2021_page_001_5d8b950ebf.jpg',
          hash: 'small_tabory_2021_page_001_5d8b950ebf',
          mime: 'image/jpeg',
          name: 'small_tábory-2021-page-001.jpg',
          path: null,
          size: 26.59,
          width: 353,
          height: 500,
          provider_metadata: {
            public_id: 'small_tabory_2021_page_001_5d8b950ebf',
            resource_type: 'image',
          },
        },
        medium: {
          ext: '.jpg',
          url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1615498173/medium_tabory_2021_page_001_5d8b950ebf.jpg',
          hash: 'medium_tabory_2021_page_001_5d8b950ebf',
          mime: 'image/jpeg',
          name: 'medium_tábory-2021-page-001.jpg',
          path: null,
          size: 51.45,
          width: 530,
          height: 750,
          provider_metadata: {
            public_id: 'medium_tabory_2021_page_001_5d8b950ebf',
            resource_type: 'image',
          },
        },
        thumbnail: {
          ext: '.jpg',
          url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1615498173/thumbnail_tabory_2021_page_001_5d8b950ebf.jpg',
          hash: 'thumbnail_tabory_2021_page_001_5d8b950ebf',
          mime: 'image/jpeg',
          name: 'thumbnail_tábory-2021-page-001.jpg',
          path: null,
          size: 3.8,
          width: 110,
          height: 156,
          provider_metadata: {
            public_id: 'thumbnail_tabory_2021_page_001_5d8b950ebf',
            resource_type: 'image',
          },
        },
      },
      hash: 'tabory_2021_page_001_5d8b950ebf',
      ext: '.jpg',
      mime: 'image/jpeg',
      size: 59.55,
      url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1615498172/tabory_2021_page_001_5d8b950ebf.jpg',
      previewUrl: null,
      provider: 'cloudinary',
      provider_metadata: {
        public_id: 'tabory_2021_page_001_5d8b950ebf',
        resource_type: 'image',
      },
      created_at: '2021-03-11T21:29:35.088Z',
      updated_at: '2021-03-11T21:29:35.103Z',
    },
  },
  {
    id: 13,
    Nazev: 'Vítáme na palubě LK Jezerka!',
    Text: '<p>Dáváte přednost méně formálnímu vzdělávání? Přihlašte své děti do <strong>Lesního klubu Jezerka</strong>!</p><p>Po 10 letech se dvě třídy původního Stromíku vydávají různými směry - první vyšlapanou cestou méně formálního vzdělávání v klubu, druhá vstupuje do rejstříku MŠMT jako Lesní mateřská škola Stromík. Lesní klub Jezerka si vysloužil název podle místa, kde působíme a bude mít stále otevřená vrátka pro rodiny, které dávají přednost méně formálnímu přístupu. Obě naše školky budou těžit z dlouholetých zkušeností vzdělávání v přírodě a navzájem se inspirovat.&nbsp;</p><p>Více informací, včetně zápisu pro příští školní rok, najdete na <a href="https://www.lesnikavyl.cz/lesniskolky">webu spolku Kavyl</a>.</p>',
    Datum: null,
    created_at: '2021-03-29T06:46:25.023Z',
    updated_at: '2021-03-29T06:46:25.044Z',
    Image: null,
  },
  {
    id: 12,
    Nazev: 'Zápis na školní rok 2021/22',
    Text: '<h3>Srdečně zveme k zápisu do Stromíku!<br>&nbsp;</h3><p>Současná situace ovlivňuje organizaci zápisů pro letošní rok, kterou na základě opatření MŠMT upravujeme následovně:</p><p>Termín: <strong>2. – 16. 5. 2021</strong></p><p>Postup pro podání přihlášky:</p><p>1. stáhněte si žádost o přijetí a dotazník v záložce <a href="/onas/dokumenty">Dokumenty</a></p><p>2. vyplněnou žádost, dotazník a kopii rodného listu nám můžete doručit v termínu 2. – 16. 5. 2021 následujícími způsoby:</p><ul><li>do datové schránky školy: itb74qd,</li><li>e-mailem s uznávaným elektronickým podpisem (nelze jen poslat prostý email!) na adresu: info@stromik.cz,</li><li>poštou na adresu: LMŠ Stromík, Hostěnická 626, Pozořice 664 07</li><li>osobně: 11. 5. 2021 od 14 - 16 h na zahradě LMŠ Stromík<br><br>Zájemci o individuální vzdělávání vyplní také <a href="/files/oznameni-iv.pdf">Oznámení o individuálním vzdělávání dítětě</a>.</li></ul><p>3. do 1. června 2021 se dozvíte, zda vaše dítě bylo přijato</p><p>Před podáním přihlášky si prosím přečtěte podrobné informace k zápisu a přijímání do Stromíku, které najdete v samostatné záložce <a href="/info/zapis">Zápis</a>. Děkujeme!<br>&nbsp;</p>',
    Datum: null,
    created_at: '2021-03-29T06:18:06.401Z',
    updated_at: '2021-03-29T06:51:00.060Z',
    Image: null,
  },
  {
    id: 9,
    Nazev: 'NAŠE AKCE - VENKU A BEZPEČNĚ',
    Text: '<p><strong>Jsme rádi, že se i v&nbsp;tomto školním roce hlásíte do našich kroužků a vzdělávacích programů. Chceme, aby návštěva našich aktivit byla pro vás nejen přínosná, ale i bezpečná</strong>.</p><p>Většina našich programů se z&nbsp;principu koná venku, v&nbsp;prostředí lesa nebo zahrady. V&nbsp;areálu pozořické hájenky <strong>důsledně dodržujeme aktuální nařízení vlády a doporučení MŠMT </strong>pro zajištění bezpečné výuky (pravidelný úklid a dezinfekce, větrání, důraz na dodržování pravidel osobní hygieny zaměstnanců i návštěvníků, ochrana úst a nosu, jednorázové ručníky). Na programech jsou účastníci v kontaktu pouze s&nbsp;našimi lektory.</p><p>Pokud nebude možné pořádat žádné vzdělávací akce z důvodu mimořádných opatření vlády či Ministerstva zdravotnictví,&nbsp;<strong>posuneme termín</strong>&nbsp;jejich konání.</p><p>U kroužků, které probíhají v&nbsp;pololetních cyklech, nabídneme náhradní termíny na všechny lekce, které nemohly proběhnout, v&nbsp;době, kdy nám to opatření umožní, tedy i v&nbsp;druhém pololetí školního roku.</p><p>Nebudete-li se moci našich aktivit zúčastnit z důvodů karantény či nemoci, můžete za sebe poslat náhradníka. Stačí nás o tom předem informovat.</p><p><strong>Storno poplatky</strong>&nbsp;u enviroprogramů pro školy máme nastaveny velmi vstřícně, nemusíte se proto bát neočekávaných situací. Programy je možné bezplatně rušit jeden pracovní den předem do 15h.</p><p>V případě, že bude seminář či jiná jednorázová akce zrušena z naší strany (např. karanténa či rozhodnutí lektora), vrátíme vám zaplacený účastnický poplatek celý.</p><p><strong>Děkujeme za vaši přízeň a těšíme se na vás i vaše děti!</strong></p>',
    Datum: '6. 9.2021',
    created_at: '2021-03-11T21:28:52.864Z',
    updated_at: '2021-09-08T14:56:34.988Z',
    Image: null,
  },
  {
    id: 16,
    Nazev: 'Naše akce 2021/22 - venku a bezpečně',
    Text: '<p><strong>Jsme rádi, že se i v&nbsp;tomto školním roce hlásíte do našich kroužků a vzdělávacích programů. Chceme, aby návštěva našich aktivit byla pro vás nejen přínosná, ale i bezpečná</strong>.</p><p>Většina našich programů se z&nbsp;principu koná venku, v&nbsp;prostředí lesa nebo zahrady. V&nbsp;areálu pozořické hájenky <strong>důsledně dodržujeme aktuální nařízení vlády a doporučení MŠMT </strong>pro zajištění bezpečné výuky (pravidelný úklid a dezinfekce, větrání, důraz na dodržování pravidel osobní hygieny zaměstnanců i návštěvníků, ochrana úst a nosu, jednorázové ručníky). Na programech jsou účastníci v kontaktu pouze s&nbsp;našimi lektory.</p><p>Pokud nebude možné pořádat žádné vzdělávací akce z důvodu mimořádných opatření vlády či Ministerstva zdravotnictví,&nbsp;<strong>posuneme termín</strong>&nbsp;jejich konání.</p><p>U kroužků, které probíhají v&nbsp;pololetních cyklech, nabídneme náhradní termíny na všechny lekce, které nemohly proběhnout, v&nbsp;době, kdy nám to opatření umožní, tedy i v&nbsp;druhém pololetí školního roku.</p><p>Nebudete-li se moci našich aktivit zúčastnit z důvodů karantény či nemoci, můžete za sebe poslat náhradníka. Stačí nás o tom předem informovat.</p><p><strong>Storno poplatky</strong>&nbsp;u enviroprogramů pro školy máme nastaveny velmi vstřícně, nemusíte se proto bát neočekávaných situací. Programy je možné bezplatně rušit jeden pracovní den předem do 15h.</p><p>V případě, že bude seminář či jiná jednorázová akce zrušena z naší strany (např. karanténa či rozhodnutí lektora), vrátíme vám zaplacený účastnický poplatek celý.</p><p><strong>Děkujeme za vaši přízeň a těšíme se na vás i vaše děti!</strong></p>',
    Datum: null,
    created_at: '2021-09-08T14:57:43.324Z',
    updated_at: '2021-09-08T14:57:43.330Z',
    Image: null,
  },
  {
    id: 14,
    Nazev: 'Výletníček',
    Text: '<p>Výletníček otvírá opět svá vrátka! Už se moc těšíme, až si vynahradíme podzimní hrátky, které jsme museli odložit na jaro.</p><p>Aktuální informace najdete na <a href="/kavyl/krouzky">Aktivity Kavylu</a>.</p><p>&nbsp;</p>',
    Datum: null,
    created_at: '2021-05-19T08:52:54.440Z',
    updated_at: '2021-05-19T08:54:57.628Z',
    Image: {
      id: 24,
      name: 'AKCE PRO VEREJNOST.JPG',
      alternativeText: '',
      caption: '',
      width: 6000,
      height: 4000,
      formats: {
        large: {
          ext: '.JPG',
          url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1621414234/large_AKCE_PRO_VEREJNOST_5c9f842227.jpg',
          hash: 'large_AKCE_PRO_VEREJNOST_5c9f842227',
          mime: 'image/jpeg',
          name: 'large_AKCE PRO VEREJNOST.JPG',
          path: null,
          size: 111.99,
          width: 1000,
          height: 667,
          provider_metadata: {
            public_id: 'large_AKCE_PRO_VEREJNOST_5c9f842227',
            resource_type: 'image',
          },
        },
        small: {
          ext: '.JPG',
          url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1621414235/small_AKCE_PRO_VEREJNOST_5c9f842227.jpg',
          hash: 'small_AKCE_PRO_VEREJNOST_5c9f842227',
          mime: 'image/jpeg',
          name: 'small_AKCE PRO VEREJNOST.JPG',
          path: null,
          size: 37.34,
          width: 500,
          height: 333,
          provider_metadata: {
            public_id: 'small_AKCE_PRO_VEREJNOST_5c9f842227',
            resource_type: 'image',
          },
        },
        medium: {
          ext: '.JPG',
          url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1621414234/medium_AKCE_PRO_VEREJNOST_5c9f842227.jpg',
          hash: 'medium_AKCE_PRO_VEREJNOST_5c9f842227',
          mime: 'image/jpeg',
          name: 'medium_AKCE PRO VEREJNOST.JPG',
          path: null,
          size: 70.5,
          width: 750,
          height: 500,
          provider_metadata: {
            public_id: 'medium_AKCE_PRO_VEREJNOST_5c9f842227',
            resource_type: 'image',
          },
        },
        thumbnail: {
          ext: '.JPG',
          url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1621414233/thumbnail_AKCE_PRO_VEREJNOST_5c9f842227.jpg',
          hash: 'thumbnail_AKCE_PRO_VEREJNOST_5c9f842227',
          mime: 'image/jpeg',
          name: 'thumbnail_AKCE PRO VEREJNOST.JPG',
          path: null,
          size: 11.09,
          width: 234,
          height: 156,
          provider_metadata: {
            public_id: 'thumbnail_AKCE_PRO_VEREJNOST_5c9f842227',
            resource_type: 'image',
          },
        },
      },
      hash: 'AKCE_PRO_VEREJNOST_5c9f842227',
      ext: '.JPG',
      mime: 'image/jpeg',
      size: 1885.04,
      url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1621414231/AKCE_PRO_VEREJNOST_5c9f842227.jpg',
      previewUrl: null,
      provider: 'cloudinary',
      provider_metadata: {
        public_id: 'AKCE_PRO_VEREJNOST_5c9f842227',
        resource_type: 'image',
      },
      created_at: '2021-05-19T08:50:35.829Z',
      updated_at: '2021-05-19T08:50:35.846Z',
    },
  },
  {
    id: 23,
    Nazev: 'Tábory 2022',
    Text: '<p>Také už se nemůžete dočkat léta a vaše děti prázdninových dobrodružství?&nbsp;</p><p>Srdečně zveme na naše příměstské tábory!</p><p>Podrobnosti najdete <a href="https://lesnikavyl.cz/tabory">zde</a>.</p><p><a href="https://docs.google.com/forms/d/e/1FAIpQLScWgFfYAO-Kq2kIQYBE_HkwfMyVLR5uMBIzB7TAHu0clYbmEA/viewform">Přihlašovat se můžete online</a>.</p><p>&nbsp;</p>',
    Datum: null,
    created_at: '2022-03-14T15:12:40.084Z',
    updated_at: '2022-03-14T15:12:40.096Z',
    Image: {
      id: 28,
      name: 'tabory22_brcal_fb_ctvrty nastrel.JPG',
      alternativeText: '',
      caption: '',
      width: 2480,
      height: 3819,
      formats: {
        large: {
          ext: '.JPG',
          url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1647270751/large_tabory22_brcal_fb_ctvrty_nastrel_c3844c36ce.jpg',
          hash: 'large_tabory22_brcal_fb_ctvrty_nastrel_c3844c36ce',
          mime: 'image/jpeg',
          name: 'large_tabory22_brcal_fb_ctvrty nastrel.JPG',
          path: null,
          size: 115.65,
          width: 649,
          height: 1000,
          provider_metadata: {
            public_id: 'large_tabory22_brcal_fb_ctvrty_nastrel_c3844c36ce',
            resource_type: 'image',
          },
        },
        small: {
          ext: '.JPG',
          url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1647270753/small_tabory22_brcal_fb_ctvrty_nastrel_c3844c36ce.jpg',
          hash: 'small_tabory22_brcal_fb_ctvrty_nastrel_c3844c36ce',
          mime: 'image/jpeg',
          name: 'small_tabory22_brcal_fb_ctvrty nastrel.JPG',
          path: null,
          size: 41.1,
          width: 325,
          height: 500,
          provider_metadata: {
            public_id: 'small_tabory22_brcal_fb_ctvrty_nastrel_c3844c36ce',
            resource_type: 'image',
          },
        },
        medium: {
          ext: '.JPG',
          url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1647270752/medium_tabory22_brcal_fb_ctvrty_nastrel_c3844c36ce.jpg',
          hash: 'medium_tabory22_brcal_fb_ctvrty_nastrel_c3844c36ce',
          mime: 'image/jpeg',
          name: 'medium_tabory22_brcal_fb_ctvrty nastrel.JPG',
          path: null,
          size: 74.73,
          width: 487,
          height: 750,
          provider_metadata: {
            public_id: 'medium_tabory22_brcal_fb_ctvrty_nastrel_c3844c36ce',
            resource_type: 'image',
          },
        },
        thumbnail: {
          ext: '.JPG',
          url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1647270750/thumbnail_tabory22_brcal_fb_ctvrty_nastrel_c3844c36ce.jpg',
          hash: 'thumbnail_tabory22_brcal_fb_ctvrty_nastrel_c3844c36ce',
          mime: 'image/jpeg',
          name: 'thumbnail_tabory22_brcal_fb_ctvrty nastrel.JPG',
          path: null,
          size: 5.99,
          width: 101,
          height: 156,
          provider_metadata: {
            public_id: 'thumbnail_tabory22_brcal_fb_ctvrty_nastrel_c3844c36ce',
            resource_type: 'image',
          },
        },
      },
      hash: 'tabory22_brcal_fb_ctvrty_nastrel_c3844c36ce',
      ext: '.JPG',
      mime: 'image/jpeg',
      size: 840.51,
      url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1647270749/tabory22_brcal_fb_ctvrty_nastrel_c3844c36ce.jpg',
      previewUrl: null,
      provider: 'cloudinary',
      provider_metadata: {
        public_id: 'tabory22_brcal_fb_ctvrty_nastrel_c3844c36ce',
        resource_type: 'image',
      },
      created_at: '2022-03-14T15:12:33.808Z',
      updated_at: '2022-03-14T15:12:33.844Z',
    },
  },
  {
    id: 24,
    Nazev: 'Den otevřených vrátek',
    Text: '<p>Myslíte si, že je pro vaše děti lesní školka to pravé?</p><p>Srdečně zveme na Den otevřených vrátek!</p><p><strong>20. dubna od 14–16 hodin</strong></p><p>Přijďte se podívat a poptat, jak to v LMŠ Stromík chodí.</p>',
    Datum: null,
    created_at: '2022-03-14T15:13:33.494Z',
    updated_at: '2022-03-14T15:13:33.501Z',
    Image: null,
  },
  {
    id: 28,
    Nazev: 'Hledáme pedagogy, průvodce 2022/23',
    Text: '<p>Chceš dětem pomáhat objevovat svět?</p><p>Hledáme pedagogy - průvodce na nový školní rok 2022/23.</p><p>nabízíme:</p><ul><li>skvělý tým a prostředí</li><li>malou skupinu dětí</li><li>práci v přírodě</li><li>plný či zkrácený pracovní úvazek dle tvých možností</li><li>příležitosti k dalšímu vzdělávání</li><li>více než 10 let zkušeností</li></ul><p>co potřebujeme:</p><ul><li>zkušenosti s pedagogikou dětí ve věku 3 - 6 let</li><li>radost ze soužití s dětmi a přírodou</li><li>odolnost - nevadí ti být venku za každého počasí</li><li>schopnost spolupracovat v týmu</li><li>flexibilitu a chuť na sobě pracovat</li></ul><p>co se hodí:</p><ul><li>umíš hrát na hudební nástroje, zpíváš, hraješ divadlo či tvoříš</li><li>jsi nadšený milovník přírody, poznáš stopy ve sněhu, ptáky na stromech…</li><li>máš za sebou vzdělávací kurzy, např. Respektovat a být respektován</li></ul><p>Máš pocit, že je to práce šitá pro tebe, ale nesplňuješ vše? Nevadí! Chceš-li se dál učit a pracovat na sobě, podpoříme tě!&nbsp;</p><p>Pošli nám životopis a krátký motivační dopis na<strong> info@stromik.cz</strong>.</p>',
    Datum: null,
    created_at: '2022-06-02T05:51:13.922Z',
    updated_at: '2022-06-08T13:12:35.864Z',
    Image: null,
  },
  {
    id: 30,
    Nazev: 'Inspekční zpráva ČŠI',
    Text: '<p>Před prázdninami nás navštívila paní inspektorka s panem inspektorem z České školní inspekce, aby zhodnotili naše celoroční snažení. Jsme moc rádi, že se jim u nás líbilo a naši vzdělávací cestu oceňují! Chcete-li si přečíst jejich zprávu, najdete ji v sekci <a href="/onas/dokumenty">Dokumenty</a>.</p>',
    Datum: null,
    created_at: '2022-06-27T15:08:21.948Z',
    updated_at: '2022-06-27T15:12:16.688Z',
    Image: null,
  },
  {
    id: 31,
    Nazev: 'PF 2023',
    Text: '<p>Přejeme krásné svátky a do nového roku pevná přátelství, zdraví a hodně sil!</p>',
    created_at: '2022-11-15T16:37:19.154Z',
    updated_at: '2022-11-15T16:37:19.166Z',
    Image: {
      name: 'NÁHLED_pf23_upravene2_gj0xwb',
      ext: '.jpg',
      mime: 'image/jpeg',
      url: 'https://res.cloudinary.com/marianka/image/upload/v1671793330/N%C3%81HLED_pf23_upravene2_gj0xwb.jpg',
      previewUrl: null,
      provider: 'cloudinary',
      created_by: 1,
      updated_by: 1,
      created_at: '2022-11-15T16:37:12.570Z',
      updated_at: '2022-11-15T16:37:12.603Z',
    },
  },
  {
    id: 32,
    Nazev: 'Řez ovocných stromů',
    Text: `<p>Chcete se naučit řezu stromů?</p> <p>Srdečně zveme na praktický workshop s potulným sadařem Janem Budkou.</p><p> 
    Kdy: v sobotu 18. 2. od 9 h</p>
    <p>Kde: u nás na pozořické hájence</p>
    <p>Přihlašovat se můžete <a href="https://1url.cz/tr0kF">zde</a>.</p>`,
    created_at: '2022-09-29T16:16:39.316Z',
    updated_at: '2022-09-29T16:18:18.645Z',
    Image: null,
  },
  {
    id: 33,
    Nazev: 'Tábory 2023',
    Text: '<p>Také už se nemůžete dočkat léta a vaše děti prázdninových dobrodružství?&nbsp;</p><p>Srdečně zveme na naše příměstské tábory!</p><p>Podrobnosti najdete <a href="https://lesnikavyl.cz/tabory">zde</a>.</p>',
    created_at: '2022-03-14T15:07:22.812Z',
    updated_at: '2022-03-14T15:08:11.512Z',
    Image: {
      url: 'https://lesnikavyl.cz/images/tabory23.jpg',
    },
  },
  {
    id: 34,
    Nazev: 'Den otevřených vrátek',
    Text: '<p>Myslíte si, že je pro vaše děti lesní školka to pravé?</p><p>Srdečně zveme na Den otevřených vrátek!</p><p><strong>13. dubna odpoledne</strong></p><p>Přijďte se podívat a poptat, jak to v LMŠ Stromík a v LK Jezerka chodí.</p><p>Zápis do LMŠ bude 10. května 2023</p>',
    created_at: '2022-03-14T15:07:22.812Z',
    updated_at: '2022-03-14T15:08:11.512Z',
    Image: null,
  },
];

export const clenove = [
  {
    id: 1,
    Jmeno: 'Klára Krchňavá',
    Pozice: 'zakladatelka a ředitelka',
    Popis:
      '<p>Narodila se a své dětství prožila v&nbsp;jižních Čechách. Vystudovala obor Speciální pedagogika na UK v&nbsp;Praze a obor Etika na Teologické fakultě Jihočeské univerzity v&nbsp;Českých Budějovicích. Vzdělání si doplňuje dalšími kurzy. Velkou inspirací jsou pro ni její tři báječné děti.</p><p>Je zakladatelkou Dětského lesního klubu Stromík v&nbsp;Pozořicích (2010) a Lesní mateřské školy Mariánka v&nbsp;Brně-Líšni (2012). Stará se o organizaci aktivit, o provoz zázemí a komunikaci s&nbsp;rodiči, je pedagog. Při obou školkách založila a střídavě také vede kroužek Výletníček a Zvoneček pro maminky s&nbsp;dětmi do tří let. V rámci celé organizace se stará o rozvoj a směřování projektů.</p><p>Spolupracuje s Asociací lesních mateřských škol na dalším vzdělávání pedagogů a organizačního vedení.</p>',
    created_at: '2021-02-23T16:21:49.589Z',
    updated_at: '2021-02-23T19:58:35.110Z',
    Poradi: 1,
    Image: {
      id: 1,
      name: 'KK_b5199eba7c.jpg',
      alternativeText: '',
      caption: '',
      width: 328,
      height: 328,
      formats: {
        thumbnail: {
          ext: '.jpg',
          url: 'https://res.cloudinary.com/marianka/image/upload/v1614097435/thumbnail_KK_b5199eba7c_90cdf368de.jpg',
          hash: 'thumbnail_KK_b5199eba7c_90cdf368de',
          mime: 'image/jpeg',
          name: 'thumbnail_KK_b5199eba7c.jpg',
          path: null,
          size: 5.79,
          width: 156,
          height: 156,
          provider_metadata: {
            public_id: 'thumbnail_KK_b5199eba7c_90cdf368de',
            resource_type: 'image',
          },
        },
      },
      hash: 'KK_b5199eba7c_90cdf368de',
      ext: '.jpg',
      mime: 'image/jpeg',
      size: 19.99,
      url: 'https://res.cloudinary.com/marianka/image/upload/v1614097434/KK_b5199eba7c_90cdf368de.jpg',
      previewUrl: null,
      provider: 'cloudinary',
      provider_metadata: {
        public_id: 'KK_b5199eba7c_90cdf368de',
        resource_type: 'image',
      },
      created_at: '2021-02-23T16:23:55.960Z',
      updated_at: '2021-02-23T16:23:55.979Z',
    },
  },
  {
    id: 5,
    Jmeno: 'Ester Úradníková',
    Pozice: 'pedagog',
    Popis:
      '<p>Narodila jsem se v Brně, kde jsem v rodinném domku prožila své dětství.<br><br>Na základní škole jsem začala chodit do Junáku - českého skautu. Díky zkušenostem a silných zážitcích s dětmi jsem se rozhodla studovat Cyrilometodějské gymnázium a Střední školu pedagogickou v Brně.<br><br>Před ukončením střední školy jsem založila oddíl v brněnské části Černovice pro děti 6–12 let.<br>Po maturitě jsem nastoupila do Dětského lesního klubu Stromík, kde uplatňuji svoje pedagogické dovednosti a znalosti.</p>',
    created_at: '2021-02-23T20:06:20.827Z',
    updated_at: '2021-09-08T14:50:43.506Z',
    Poradi: 3,
    Image: {
      id: 5,
      name: 'Ester Úradníková.jpeg',
      alternativeText: '',
      caption: '',
      width: 491,
      height: 459,
      formats: {
        thumbnail: {
          ext: '.jpeg',
          url: 'https://res.cloudinary.com/marianka/image/upload/v1614110776/thumbnail_Ester_Uradnikova_56d6c87100.jpg',
          hash: 'thumbnail_Ester_Uradnikova_56d6c87100',
          mime: 'image/jpeg',
          name: 'thumbnail_Ester Úradníková.jpeg',
          path: null,
          size: 6.57,
          width: 167,
          height: 156,
          provider_metadata: {
            public_id: 'thumbnail_Ester_Uradnikova_56d6c87100',
            resource_type: 'image',
          },
        },
      },
      hash: 'Ester_Uradnikova_56d6c87100',
      ext: '.jpeg',
      mime: 'image/jpeg',
      size: 31.05,
      url: 'https://res.cloudinary.com/marianka/image/upload/v1614110775/Ester_Uradnikova_56d6c87100.jpg',
      previewUrl: null,
      provider: 'cloudinary',
      provider_metadata: {
        public_id: 'Ester_Uradnikova_56d6c87100',
        resource_type: 'image',
      },
      created_at: '2021-02-23T20:06:16.897Z',
      updated_at: '2021-02-23T20:06:16.916Z',
    },
  },
  {
    id: 2,
    Jmeno: 'Martina Hujová',
    Pozice: 'pedagog',
    Popis:
      '<p>Narodila jsem se v Opavě, kde jsem také vyrůstala. Vystudovala jsem bakalářský obor Sociální pedagogika ve Zlíně a pokračovala v magisterském studiu v Brně. Díky Erasmu jsem si také vyzkoušela, jak se studuje v Portugalsku. Už během studia mě zajímaly různé cesty alternativního vzdělávání a ve své diplomové práci jsem se zabývala unschoolingem.&nbsp;</p><p>Během studia jsem působila v nízkoprahovém centru pro děti ve Zlíně, jako dobrovolník při středisku výchovné péče ve Zlíně, jako dobrovolník na odlehčovacích pobytech pro dívky s Rettovým syndromem a podílela jsem se na vytváření výukových metod pro děti s autismem</p><p>V lesní školce se mi líbí svoboda, kterou zažíváme s dětmi v lese, učení se prožitkem, blízkost k přírodě. Pozorovat věci, takové jaké doopravdy jsou je, dle mého názoru, nejlepší způsob, jak se o nich učit.&nbsp;</p><p>Motto” ...kdybych já měl padesáttři minut nazbyt, šel bych se úplně pomaloučku projít ke studánce..” Malý Princ</p>',
    created_at: '2021-02-23T20:00:26.882Z',
    updated_at: '2021-03-10T14:29:56.633Z',
    Poradi: 2,
    Image: {
      id: 2,
      name: 'marta_279d72631a.jpg',
      alternativeText: '',
      caption: '',
      width: 820,
      height: 820,
      formats: {
        small: {
          ext: '.jpg',
          url: 'https://res.cloudinary.com/marianka/image/upload/v1614110415/small_marta_279d72631a_488eaedf48.jpg',
          hash: 'small_marta_279d72631a_488eaedf48',
          mime: 'image/jpeg',
          name: 'small_marta_279d72631a.jpg',
          path: null,
          size: 43.17,
          width: 500,
          height: 500,
          provider_metadata: {
            public_id: 'small_marta_279d72631a_488eaedf48',
            resource_type: 'image',
          },
        },
        medium: {
          ext: '.jpg',
          url: 'https://res.cloudinary.com/marianka/image/upload/v1614110414/medium_marta_279d72631a_488eaedf48.jpg',
          hash: 'medium_marta_279d72631a_488eaedf48',
          mime: 'image/jpeg',
          name: 'medium_marta_279d72631a.jpg',
          path: null,
          size: 81.02,
          width: 750,
          height: 750,
          provider_metadata: {
            public_id: 'medium_marta_279d72631a_488eaedf48',
            resource_type: 'image',
          },
        },
        thumbnail: {
          ext: '.jpg',
          url: 'https://res.cloudinary.com/marianka/image/upload/v1614110413/thumbnail_marta_279d72631a_488eaedf48.jpg',
          hash: 'thumbnail_marta_279d72631a_488eaedf48',
          mime: 'image/jpeg',
          name: 'thumbnail_marta_279d72631a.jpg',
          path: null,
          size: 6.43,
          width: 156,
          height: 156,
          provider_metadata: {
            public_id: 'thumbnail_marta_279d72631a_488eaedf48',
            resource_type: 'image',
          },
        },
      },
      hash: 'marta_279d72631a_488eaedf48',
      ext: '.jpg',
      mime: 'image/jpeg',
      size: 91.14,
      url: 'https://res.cloudinary.com/marianka/image/upload/v1614110412/marta_279d72631a_488eaedf48.jpg',
      previewUrl: null,
      provider: 'cloudinary',
      provider_metadata: {
        public_id: 'marta_279d72631a_488eaedf48',
        resource_type: 'image',
      },
      created_at: '2021-02-23T20:00:15.749Z',
      updated_at: '2021-02-23T20:00:15.779Z',
    },
  },
  {
    id: 7,
    Jmeno: 'Libor Brzobohatý',
    Pozice: 'pedagog',
    Popis:
      '<p>Svůj dosavadní život prožil v Brně, kde vystudoval gymnázium a později divadelní dramaturgii na JAMU. Nejdobrodružnější část dětství prožil ve skautském oddíle, který později vedl a nyní se v Junáku věnuje vzdělávání. V neziskové organizaci Nesehnutí působil jako zdravotník a lektor táborů pro děti z příchozích rodin z celého světa. Potřeba kontaktu s přírodou a dětmi ho zavála do Stromíku, kde spokojeně pobíhá po lese od roku 2019.</p>',
    created_at: '2021-03-06T12:15:59.720Z',
    updated_at: '2021-03-06T12:19:38.533Z',
    Poradi: 7,
    Image: {
      id: 14,
      name: 'LB.jpg',
      alternativeText: '',
      caption: '',
      width: 814,
      height: 814,
      formats: {
        small: {
          ext: '.jpg',
          url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1615033175/small_LB_febdc94ebd.jpg',
          hash: 'small_LB_febdc94ebd',
          mime: 'image/jpeg',
          name: 'small_LB.jpg',
          path: null,
          size: 22.88,
          width: 500,
          height: 500,
          provider_metadata: {
            public_id: 'small_LB_febdc94ebd',
            resource_type: 'image',
          },
        },
        medium: {
          ext: '.jpg',
          url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1615033174/medium_LB_febdc94ebd.jpg',
          hash: 'medium_LB_febdc94ebd',
          mime: 'image/jpeg',
          name: 'medium_LB.jpg',
          path: null,
          size: 45.39,
          width: 750,
          height: 750,
          provider_metadata: {
            public_id: 'medium_LB_febdc94ebd',
            resource_type: 'image',
          },
        },
        thumbnail: {
          ext: '.jpg',
          url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1615033173/thumbnail_LB_febdc94ebd.jpg',
          hash: 'thumbnail_LB_febdc94ebd',
          mime: 'image/jpeg',
          name: 'thumbnail_LB.jpg',
          path: null,
          size: 3.71,
          width: 156,
          height: 156,
          provider_metadata: {
            public_id: 'thumbnail_LB_febdc94ebd',
            resource_type: 'image',
          },
        },
      },
      hash: 'LB_febdc94ebd',
      ext: '.jpg',
      mime: 'image/jpeg',
      size: 50.29,
      url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1615033172/LB_febdc94ebd.jpg',
      previewUrl: null,
      provider: 'cloudinary',
      provider_metadata: { public_id: 'LB_febdc94ebd', resource_type: 'image' },
      created_at: '2021-03-06T12:19:35.510Z',
      updated_at: '2021-03-06T12:19:35.527Z',
    },
  },
];

export const sponzori = [
  {
    id: 1,
    Nazev: 'MŠMT',
    Vyska: null,
    Poradi: 1,
    Odkaz: 'http://www.msmt.cz/',
    Okraj: null,
    created_at: '2021-03-01T23:20:05.994Z',
    updated_at: '2021-03-01T23:21:00.584Z',
    Popis: null,
    Image: {
      id: 7,
      name: 'msmt_e0e6a7cb57.jpg',
      alternativeText: '',
      caption: '',
      width: 653,
      height: 367,
      formats: {
        small: {
          ext: '.jpg',
          url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1614640800/small_msmt_e0e6a7cb57_b20fc86349.jpg',
          hash: 'small_msmt_e0e6a7cb57_b20fc86349',
          mime: 'image/jpeg',
          name: 'small_msmt_e0e6a7cb57.jpg',
          path: null,
          size: 13.76,
          width: 500,
          height: 281,
          provider_metadata: {
            public_id: 'small_msmt_e0e6a7cb57_b20fc86349',
            resource_type: 'image',
          },
        },
        thumbnail: {
          ext: '.jpg',
          url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1614640799/thumbnail_msmt_e0e6a7cb57_b20fc86349.jpg',
          hash: 'thumbnail_msmt_e0e6a7cb57_b20fc86349',
          mime: 'image/jpeg',
          name: 'thumbnail_msmt_e0e6a7cb57.jpg',
          path: null,
          size: 5.15,
          width: 245,
          height: 138,
          provider_metadata: {
            public_id: 'thumbnail_msmt_e0e6a7cb57_b20fc86349',
            resource_type: 'image',
          },
        },
      },
      hash: 'msmt_e0e6a7cb57_b20fc86349',
      ext: '.jpg',
      mime: 'image/jpeg',
      size: 18.15,
      url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1614640799/msmt_e0e6a7cb57_b20fc86349.jpg',
      previewUrl: null,
      provider: 'cloudinary',
      provider_metadata: {
        public_id: 'msmt_e0e6a7cb57_b20fc86349',
        resource_type: 'image',
      },
      created_at: '2021-03-01T23:20:00.911Z',
      updated_at: '2021-03-01T23:20:00.962Z',
    },
  },
  {
    id: 5,
    Nazev: 'Livebox',
    Vyska: null,
    Poradi: 5,
    Odkaz: 'http://www.livebox.cz/',
    Okraj: 2,
    created_at: '2021-03-01T23:22:32.308Z',
    updated_at: '2021-03-01T23:24:52.880Z',
    Popis: null,
    Image: {
      id: 11,
      name: 'livebox_3cf08dc656.gif',
      alternativeText: '',
      caption: '',
      width: 183,
      height: 46,
      formats: null,
      hash: 'livebox_3cf08dc656_e3f13b0461',
      ext: '.gif',
      mime: 'image/gif',
      size: 1.7,
      url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1614640941/livebox_3cf08dc656_e3f13b0461.gif',
      previewUrl: null,
      provider: 'cloudinary',
      provider_metadata: {
        public_id: 'livebox_3cf08dc656_e3f13b0461',
        resource_type: 'image',
      },
      created_at: '2021-03-01T23:22:21.701Z',
      updated_at: '2021-03-01T23:22:21.743Z',
    },
  },
  {
    id: 6,
    Nazev: 'Slavkov',
    Vyska: null,
    Poradi: 6,
    Odkaz: 'https://www.mas-slavkovskebojiste.cz/',
    Okraj: null,
    created_at: '2021-03-01T23:28:53.404Z',
    updated_at: '2021-03-01T23:28:53.440Z',
    Popis: null,
    Image: {
      id: 12,
      name: 'bojiste.png',
      alternativeText: '',
      caption: '',
      width: 400,
      height: 312,
      formats: {
        thumbnail: {
          ext: '.png',
          url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1614641329/thumbnail_bojiste_a28ff9d78c.png',
          hash: 'thumbnail_bojiste_a28ff9d78c',
          mime: 'image/png',
          name: 'thumbnail_bojiste.png',
          path: null,
          size: 16.02,
          width: 200,
          height: 156,
          provider_metadata: {
            public_id: 'thumbnail_bojiste_a28ff9d78c',
            resource_type: 'image',
          },
        },
      },
      hash: 'bojiste_a28ff9d78c',
      ext: '.png',
      mime: 'image/png',
      size: 7.51,
      url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1614641328/bojiste_a28ff9d78c.png',
      previewUrl: null,
      provider: 'cloudinary',
      provider_metadata: {
        public_id: 'bojiste_a28ff9d78c',
        resource_type: 'image',
      },
      created_at: '2021-03-01T23:28:49.734Z',
      updated_at: '2021-03-01T23:28:49.750Z',
    },
  },
  {
    id: 3,
    Nazev: 'Pozořice',
    Vyska: null,
    Poradi: 3,
    Odkaz: 'http://www.pozorice.cz/',
    Okraj: null,
    created_at: '2021-03-01T23:21:34.143Z',
    updated_at: '2021-03-07T12:12:16.760Z',
    Popis: 'Pozořice',
    Image: {
      id: 9,
      name: 'logo_pozorice_e54e4199ee.jpg',
      alternativeText: '',
      caption: '',
      width: 214,
      height: 235,
      formats: {
        thumbnail: {
          ext: '.jpg',
          url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1614640878/thumbnail_logo_pozorice_e54e4199ee_d3dd608ba9.jpg',
          hash: 'thumbnail_logo_pozorice_e54e4199ee_d3dd608ba9',
          mime: 'image/jpeg',
          name: 'thumbnail_logo_pozorice_e54e4199ee.jpg',
          path: null,
          size: 6.41,
          width: 142,
          height: 156,
          provider_metadata: {
            public_id: 'thumbnail_logo_pozorice_e54e4199ee_d3dd608ba9',
            resource_type: 'image',
          },
        },
      },
      hash: 'logo_pozorice_e54e4199ee_d3dd608ba9',
      ext: '.jpg',
      mime: 'image/jpeg',
      size: 11.95,
      url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1614640877/logo_pozorice_e54e4199ee_d3dd608ba9.jpg',
      previewUrl: null,
      provider: 'cloudinary',
      provider_metadata: {
        public_id: 'logo_pozorice_e54e4199ee_d3dd608ba9',
        resource_type: 'image',
      },
      created_at: '2021-03-01T23:21:18.324Z',
      updated_at: '2021-03-01T23:21:18.357Z',
    },
  },
  {
    id: 4,
    Nazev: 'Viničné Šumice',
    Vyska: null,
    Poradi: 4,
    Odkaz: 'https://www.vinicne-sumice.cz/',
    Okraj: null,
    created_at: '2021-03-01T23:22:05.925Z',
    updated_at: '2021-03-07T12:12:32.246Z',
    Popis: 'Viničné Šumice',
    Image: {
      id: 10,
      name: 'vinicne_sumice_1f319f3ac7.png',
      alternativeText: '',
      caption: '',
      width: 334,
      height: 400,
      formats: {
        thumbnail: {
          ext: '.png',
          url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1614640916/thumbnail_vinicne_sumice_1f319f3ac7_cb956515da.png',
          hash: 'thumbnail_vinicne_sumice_1f319f3ac7_cb956515da',
          mime: 'image/png',
          name: 'thumbnail_vinicne_sumice_1f319f3ac7.png',
          path: null,
          size: 26.21,
          width: 130,
          height: 156,
          provider_metadata: {
            public_id: 'thumbnail_vinicne_sumice_1f319f3ac7_cb956515da',
            resource_type: 'image',
          },
        },
      },
      hash: 'vinicne_sumice_1f319f3ac7_cb956515da',
      ext: '.png',
      mime: 'image/png',
      size: 129.38,
      url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1614640915/vinicne_sumice_1f319f3ac7_cb956515da.png',
      previewUrl: null,
      provider: 'cloudinary',
      provider_metadata: {
        public_id: 'vinicne_sumice_1f319f3ac7_cb956515da',
        resource_type: 'image',
      },
      created_at: '2021-03-01T23:21:56.683Z',
      updated_at: '2021-03-01T23:21:56.713Z',
    },
  },
  {
    id: 2,
    Nazev: 'JMK',
    Vyska: '',
    Poradi: 2,
    Odkaz: 'https://www.kr-jihomoravsky.cz/',
    Okraj: null,
    created_at: '2021-03-01T23:20:47.788Z',
    updated_at: '2022-02-09T15:07:40.298Z',
    Popis: null,
    Image: {
      id: 8,
      name: 'jmk.png',
      alternativeText: '',
      caption: '',
      width: 4155,
      height: 995,
      formats: {
        large: {
          ext: '.png',
          url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1644419253/large_jmk_21aa6ec4e9.png',
          hash: 'large_jmk_21aa6ec4e9',
          mime: 'image/png',
          name: 'large_jmk.png',
          path: null,
          size: 50.84,
          width: 1000,
          height: 239,
          provider_metadata: {
            public_id: 'large_jmk_21aa6ec4e9',
            resource_type: 'image',
          },
        },
        small: {
          ext: '.png',
          url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1644419255/small_jmk_21aa6ec4e9.png',
          hash: 'small_jmk_21aa6ec4e9',
          mime: 'image/png',
          name: 'small_jmk.png',
          path: null,
          size: 21.36,
          width: 500,
          height: 120,
          provider_metadata: {
            public_id: 'small_jmk_21aa6ec4e9',
            resource_type: 'image',
          },
        },
        medium: {
          ext: '.png',
          url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1644419255/medium_jmk_21aa6ec4e9.png',
          hash: 'medium_jmk_21aa6ec4e9',
          mime: 'image/png',
          name: 'medium_jmk.png',
          path: null,
          size: 36.2,
          width: 750,
          height: 180,
          provider_metadata: {
            public_id: 'medium_jmk_21aa6ec4e9',
            resource_type: 'image',
          },
        },
        thumbnail: {
          ext: '.png',
          url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1644419251/thumbnail_jmk_21aa6ec4e9.png',
          hash: 'thumbnail_jmk_21aa6ec4e9',
          mime: 'image/png',
          name: 'thumbnail_jmk.png',
          path: null,
          size: 7.83,
          width: 245,
          height: 58,
          provider_metadata: {
            public_id: 'thumbnail_jmk_21aa6ec4e9',
            resource_type: 'image',
          },
        },
      },
      hash: 'jmk_21aa6ec4e9',
      ext: '.png',
      mime: 'image/png',
      size: 136.47,
      url: 'https://res.cloudinary.com/dugmue8nu/image/upload/v1644419250/jmk_21aa6ec4e9.png',
      previewUrl: null,
      provider: 'cloudinary',
      provider_metadata: {
        public_id: 'jmk_21aa6ec4e9',
        resource_type: 'image',
      },
      created_at: '2021-03-01T23:20:29.907Z',
      updated_at: '2022-02-09T15:07:36.265Z',
    },
  },
];

export const stranky = [
  {
    id: 2,
    Nazev: 'Zázemí 1',
    Text: '<p>Zázemí Stromíku tvoří rozhlehlá zahrada. Na zahradě jsou prolézačky, houpačky, skluzavka. Máme tu ovocné stromy a také záhonky na nichž pěstujeme bylinky i zeleninu. Podél zahrady jsou vysázeny ovocné jedlé keře, které v létě lákají k mlsání.&nbsp;</p>',
    created_at: '2021-02-23T20:11:44.388Z',
    updated_at: '2021-03-18T08:20:17.192Z',
  },
  {
    id: 10,
    Nazev: 'Přednášky',
    Text: '<p>Srdečně zveme také na přednášky pro rodiče i širokou veřejnost o vzdělávání a výchově. Pozvánky najdete u nás a na <a href="https://www.lesnikavyl.cz/">webu</a> či <a href="https://www.facebook.com/spolekKavyl">FB</a> spolku Kavyl.</p>',
    created_at: '2021-02-23T20:25:57.911Z',
    updated_at: '2021-02-23T20:25:57.917Z',
  },
  {
    id: 13,
    Nazev: 'Kontakt1',
    Text: '<h3>Kde nás najdete</h3><p>Hostěnická 626, 664 07 Pozořice</p>',
    created_at: '2021-02-23T20:27:31.682Z',
    updated_at: '2021-02-28T16:28:13.100Z',
  },
  {
    id: 8,
    Nazev: 'Naše pravidla',
    Text: '<ol><li>Nenosíme do školky žádné sladkosti, sladké čaje a hračky.</li><li>Přicházíme do školky zdravé.</li><li>Máme dostatečné vybavení do přírody s ohledem na roční dobu.</li><li>Přicházíme do školky včas a rodiče si nás také včas vyzvedávají.</li><li>Rodiče jsou v době pobytu dítěte ve školce na telefonu pro případ zhoršení zdravotního stavu, úrazu, změny místa vyzvedávání apod.</li></ol>',
    created_at: '2021-02-23T20:24:38.266Z',
    updated_at: '2021-03-05T08:26:52.001Z',
  },
  {
    id: 3,
    Nazev: 'Program 1',
    Text: '<p>Převážná většina programu ve Stromíku probíhá celoročně a za každého počasí venku, tj. na zahradě s ovocnými stromy v našem zázemí a v blízkém smíšeném lese. Les vnímáme jako přirozené, člověkem (a pedagogem) nepřipravené prostředí, které samo o sobě nabízí prostor pro kreativitu, rytmus a harmonii. V přírodě člověk snadno a přirozeně vnímá střídání ročních období, rytmus přirozeného světla a cítí vliv těchto změn na nás samotné. Proto jsme náš program uzpůsobili koloběhu roku a tradicím. Věnujeme se slavnostem inspirovaným Waldorfskou pedagogikou, které s každým novým rokem s dětmi prožíváme a znovuvytváříme podle aktuálních potřeb skupiny dětí i dospělých.</p><h3>Harmonogram dne:</h3><figure class="table"><table><tbody><tr><td>7:30 - 8:30</td><td>příjezd dětí s rodiči, převzetí dětí</td></tr><tr><td>8:45 - 9:00</td><td>přivítání s dětmi, ranní diskuzní kruh, seznámení s programem</td></tr><tr><td>9:00 - 10:00</td><td>cesta do lesa, dopolední řízená činnost v lese</td></tr><tr><td>10:00 - 10:30</td><td>dopolední svačina dětí, volná hra dětí</td></tr><tr><td>10:30 - 11:30</td><td>společná hra dětí v lese, pedagog je dětem průvodcem</td></tr><tr><td>11:30 - 12:00</td><td>zpáteční cesta do zázemí</td></tr><tr><td>12:00 - 12:45</td><td>PŘESTÁVKA NA OBĚD</td></tr><tr><td>12:45 - 13:30</td><td>polední odpočinek, klidová činnost</td></tr><tr><td>13:30 - 15:30</td><td>odpolední činnost a volná hra dětí na zahradě, svačina dle potřeb dětí</td></tr><tr><td>15:30 - 16:00</td><td>předání dětí rodičům</td></tr></tbody></table></figure>',
    created_at: '2021-02-23T20:12:44.259Z',
    updated_at: '2021-03-10T22:52:11.487Z',
  },
  {
    id: 14,
    Nazev: 'Paticka',
    Text: '<h4><a href="mailto:stromik@stromik.cz">info@stromik.cz</a></h4><h4>Hostěnická 626, Pozořice</h4><h4>bus č. 701, zastávka Pozořice, vodojem</h4><h4><a href="tel:+420777145343">777 145 343</a></h4><h4><a href="https://wwww.facebook.com/stromik">stromik</a></h4>',
    created_at: '2021-02-23T20:51:55.167Z',
    updated_at: '2021-02-25T07:46:11.623Z',
  },
  {
    id: 15,
    Nazev: 'O Stromíku 2',
    Text: '<h2>Co nabízíme</h2><ul><li>předškolní vzdělávání pro děti od 3 let</li><li>jsme pro děti otevřeni každý všední den od 7:30 do 16:00</li><li>vycházíme z lesní pedagogiky a konceptu Respektovat a být respektován</li><li>zázemí školky tvoří jurta, týpí a velká zahrada v blízkosti lesa</li><li>program realizujeme převážně v přírodě</li><li>nabízíme přátelské a otevřené prostředí všem dětem, rodičům a pedagogům</li><li>řadu kroužků a zájmových činností v průběhu týdne</li></ul><h2>Z čeho vycházíme</h2><p>Vycházíme z Rámcového vzdělávacího programu pro mateřské školy vydaného MŠMT. Na jeho podkladě vytváříme školní vzdělávací program přizpůsobený potřebám dětí. Inspirovali jsme se koncepcí lesních mateřských škol v zahraničí.&nbsp;<br>Naše pedagogická koncepce je založena na myšlence " s dětmi venku za každého počasí, bez zdí a plotů". Při provázení dětí poznáváním a učením využíváme rozmanitého prostředí lesa, který nabízí široké možnosti pro rozvoj všech klíčových kompetencí dětí. &nbsp;Opírá se o:&nbsp;</p><ul><li>metody prožitkového učení</li><li>podporu přirozeného pozorování, experimenty – pedagog je dítěti průvodcem v jeho vlastním poznávání, podporuje jeho přirozenou zvídavost a tím mu pomáhá rozvíjet znalosti a dovednosti</li><li>volnou hru – jako přirozený proces učení – spontánní hra dětí, cílevědomé zařazení společné hry s danou tématikou</li><li>rituály - každý den v lese je doprovázen rituály, které dávají dětem jistotu a hranice, děti se lépe orientují v čase.&nbsp;</li><li>drama-terapeutické metody – děti provází látkový maňásek – lesní skřítek, který každý den vítá děti. Děti se učí projevovat vlastní pocity pomocí divadelních prvků.</li><li>prvky Waldorfské pedagogiky a dalších alternativních pedagogických směrů</li></ul>',
    created_at: '2021-02-28T16:35:23.577Z',
    updated_at: '2021-03-10T15:15:50.201Z',
  },
  {
    id: 9,
    Nazev: 'Kroužky',
    Text: '<h3>Výletníček</h3><p>Na jaře, na podzim a v zimě probíhá cyklus setkání určených pro děti do 3 let v doprovodu rodiče nebo jiné blízké osoby. Od malička děti poznávají přírodu hravou formou - písničky, básničky, tvoření, hry, procházky. Hrajeme si v naší kouzelné zahradě a v blízkém lese pod vedením lektora z lesní školky.</p><h3>Aktuální cyklus</h3><p>Přihlašovací formulář zde.&nbsp;<br>&nbsp;</p>',
    created_at: '2021-02-23T20:25:25.497Z',
    updated_at: '2022-09-16T08:57:12.593Z',
  },
  {
    id: 16,
    Nazev: 'Projekty 1',
    Text: '<h3>NNO Slavkovské bojiště v přírodě (2020–23)</h3><p>Prostřednictvím našeho zřizovatele se podílíme na projektu <a href="https://slavkovskebojiste.cz/"><strong>MAS Slavkovské bojiště</strong></a>, který má za cíl podpořit nabídku neformálního vzdělávání a zvýšit jeho kvalitu na území MAS Slavkovské bojiště. V rámci projektu chceme sdílet zkušenosti s přírodní pedagogikou a obohatit se o zkušenosti s jinými metodami vzdělávání, rozvinout nové poznatky v programech zaměřených na environmentální výchovu a zvýšit kvalifikaci našich lektorů.</p><h3>Digitalizujeme školu</h3><div style="display: flex; justify-content: center"><img src="/images/digitalizujeme.png"></div><p>&nbsp;</p>',
    created_at: '2021-02-28T16:39:47.513Z',
    updated_at: '2021-03-18T08:27:14.238Z',
  },
  {
    id: 18,
    Nazev: 'Zázemí 2',
    Text: '<p>Jako zázemí k odpočinku či při nepřízni počasí nám slouží útulná jurta, v níž vás do kouta nikdo nepostaví.&nbsp;<br>Hned za zahradou se rozprostírá les, kam vyrážíme za poznáváním i dobrodružstvím.</p>',
    created_at: '2021-03-01T22:48:15.694Z',
    updated_at: '2021-03-10T15:19:50.208Z',
  },
  {
    id: 19,
    Nazev: 'Program 2',
    Text: '<h3>Kroužky a předškolní příprava</h3><p>V rámci kroužků a pravidelně organizovaných aktivit nabízíme muzikoterapii s bubnováním, výtvarný kroužek, jízdu na koni, angličtinu, aktivity spojené s prvky divadelní výchovy, práci s ostrými nástroji.&nbsp;</p><p>Předškolní přípravě se věnujeme podle potřeb dítěte v rámci aktivit během celého týdne. Zároveň se věnujeme také soustředěné předškolní přípravě zaměřené na cílený rozvoj klíčových kompetencí předškoláka. Součástí každodenního programu jsou písničky, básničky, pohybové hry na rozvoj motoriky i logopedická cvičení.&nbsp;</p>',
    created_at: '2021-03-01T22:49:21.078Z',
    updated_at: '2021-03-10T15:26:32.671Z',
  },
  {
    id: 17,
    Nazev: 'Jak se žije',
    Text: '<p><a href="/images/jsz_rozcestnik.jpg">Žijeme v bezpečném světě.</a></p><ul><li><a href="/images/jsz_pravidla.jpg">Máme jasná pravidla a hranice.</a></li><li><a href="/images/jsz_postup.jpg">Postupujeme od lehkého po obtížné.</a></li><li><a href="/images/jsz_komentujeme.jpg">V rizikových situacích jdeme příkladem a svůj postup nahlas komentujeme.</a></li><li><a href="/images/jsz_riziko.jpg">Pracujeme s bezpečným rizikem.</a></li><li><a href="/images/jsz_bezpecny_prostor.jpg">Vytváříme bezpečný prostor pro svobodný dětský vývoj.</a></li></ul>',
    created_at: '2021-02-28T18:03:33.361Z',
    updated_at: '2021-05-28T07:58:10.537Z',
  },
  {
    id: 7,
    Nazev: 'Co s sebou 1',
    Text: '<p><strong>Oblečení</strong><br>K ochraně před sluncem, poškrábáním a klíšťaty oblékat dětem vždy dlouhé nohavice a rukávy. Nezbytná je pokrývka hlavy, nejlépe chránící i krk.</p><p><strong>Co v zimě</strong><br>Zásada cibulovitého vrstvení, tj. víc vrstev, které se mohou podle potřeby měnit, vysvlékat nebo oblékat. Spodní vrstva hřejivá, ideální je vlna. Poté následují 1 – 3 vrstvy z fleecového materiálu, které hřejí a zároveň izolují. Vrstvy neprofouknou a udržují stabilní teplotu. Svrchní vrstva má především funkci nepromokavou.</p><p>Důležité je i vrstvení nohou, dobré je mít na nepromokavých kalhotách gumičku, která se dá přetáhnout přes boty, nebo dát dítěti návleky na boty.</p><p>Boty nejlépe s membránou a pevné kotníčkové. Za deště a bláta lze použít holínky.</p><p><strong>Co do batohu</strong><br>Batoh by měl být z pevného a nejlépe nepromokavého materiálu, s nastavitelnými pruhy. Velmi dobrá je náprsní přezka, která zajistí, že dětem při pohybu batoh nepadá z ramen.</p><p>Do batůžku přijde podložka na sezení – stačí ustřižená karimatka, svačinka, pití, kapesník, náhradní spodní prádlo a ponožky, v zimě náhradní rukavice, sáček na poklady z lesa.</p><p>Náhradní oblečení (zůstává v místě zázemí) – spodní prádlo, ponožky, punčochy, tepláky, tričko, mikina, náhradní obuv na ven, papuče – viditelně označit a doplňovat.</p>',
    created_at: '2021-02-23T20:24:11.711Z',
    updated_at: '2021-03-01T22:52:59.545Z',
  },
  {
    id: 21,
    Nazev: 'Aktivity Kavylu',
    Text: '<p>Spolek Kavyl z.s., zřizovatel Stromíku, pořádá v našem zázemí volnočasové kroužky, přednášky, semináře a letní příměstské tábory.&nbsp;</p>',
    created_at: '2021-03-01T22:54:50.577Z',
    updated_at: '2022-04-20T11:12:48.747Z',
  },
  {
    id: 6,
    Nazev: 'Ceník',
    Text: '<h3>Docházka</h3><p>Za dítě umístěné v naší lesní mateřské škole lze od školního roku 2021–22 za kalendářní rok uplatnit odpočet na dani (za kalendářní rok 2022 to bude až 16 200 Kč). Tento odpočet je vyřizován individuálně &nbsp;v rámci daňového přiznání.&nbsp;</p><figure class="table"><table><thead><tr><th>Model docházky</th><th>&nbsp;Za měsíc</th></tr></thead><tbody><tr><td>Celotýdenní</td><td>&nbsp;7 000 Kč (5 380 Kč po odpočtu)</td></tr><tr><td>Třídenní</td><td>&nbsp;5 500 Kč (3 880 Kč po odpočtu)</td></tr><tr><td>Dvoudenní</td><td>&nbsp;4 000 Kč (2 380 Kč po odpočtu)</td></tr></tbody></table></figure><p>V ceně není zahrnuto stravování.&nbsp;</p><h3><strong>Nahrazování nemocí</strong></h3><p>Řádná omluva daného dne docházky je do 8 hodin ráno přes interní docházkový systém. Pokud dojde k řádné omluvě do 13 hodin předchozího dne, je do náhrady započítáván i oběd.</p><p>Náhrada je možná po zadání v systému na kterýkoli jiný den v týdnu s ohledem na volnou kapacitu skupiny.</p><p>Není možné odhlásit dítě z pravidelné docházky a nahrazovat si pouze nemoci. Náhrady je možné uplatnit pouze do konce aktuálního školního roku.</p><p><br>&nbsp;</p>',
    created_at: '2021-02-23T20:23:20.571Z',
    updated_at: '2022-03-04T14:41:29.465Z',
  },
  {
    id: 5,
    Nazev: 'Zápis',
    Text: '<h3>Informace k zápisu</h3><p><i>Zápis pro školní rok 2022/23</i></p><ul><li><i>Den otevřených dveří: 20. dubna 2022 14 – 16 h</i></li><li><i>Zápis: 12. května 2022 14 – 16 h</i></li></ul><p><i>Kontakt: 604 523 160 - Jindra Klemešová, koordinátorka</i></p><p>Do naší lesní mateřské školy jsou přijímány děti ve věku 3 - 6 let do maximální kapacity 16 dětí.</p><h3>POSTUP PRO PŘIHLAŠOVÁNÍ</h3><ol><li>vyplňte předběžný <a href="https://docs.google.com/forms/d/e/1FAIpQLSf-4sPrqYMSd40wO8PAPfTSjqUrQG6qlhB5Nknz7JdvWObEhA/viewform?usp=sf_link">nezávazný vstupní dotaznik</a></li><li>pozveme vás na informační schůzku, můžete se také k nám přijít podívat na Den otevřených dveří</li><li>stáhněte si žádost o přijetí a dotazník v záložce <a href="/onas/dokumenty">Dokumenty</a></li><li>nechte si žádost potvrdit od lékaře</li><li>vyplněnou žádost, dotazník a kopii rodného listu nám doručte:</li></ol><ul><li>buď <strong>osobně</strong> v době zápisu <strong>12. května 2022 od 14 do 16 h</strong></li><li>nebo<strong> po předchozí osobní schůzce poštou nebo datovou schránkou </strong>v termínu <strong>2. – 16. května 2022</strong></li></ul><p>&nbsp; &nbsp; &nbsp; 6. začátkem června dostanete rozhodnutí o přijetí</p><p><strong>Aktuální termíny</strong> Dne otevřených dveří i zápisu najdete na našem webu a <a href="https://www.facebook.com/Stromik">FB</a>.</p><p>Chcete-li vaše dítě přihlásit v průběhu školního roku, informujte se u koordinátorky o volných místech.</p><p>Před podáním žádosti se prosím seznamte s obsahem našich webových stránek a dokumentů. Vedle praktických informací o nás, programu i provozu, si na webu můžete přečíst také všechny důležité dokumenty - provozní a školní řád, školní vzdělávací program, podrobné podmínky pro přijímání dětí a další.</p><p>Upozorňujeme, že LMŠ Stromík přijímá děti, které jsou řádně očkované (rodiče dodají potvrzení od lékaře, nebo potvrzení o zdravotní kontraindikaci podle § 50 zák. č. 258/2000 Sb. o ochraně veřejného zdraví).</p><p>Informace k poplatkům za vzdělávání najdete v záložce <a href="/info/cenik">Ceník a stravování.</a></p><p>Na přijetí dítěte do LMŠ Stromík není nárok. O přijetí dětí rozhoduje ředitelka LMŠ podle <a href="/files/kriteria_prijeti_2022.pdf">stanovených kritérií</a>.</p><p>Chcete-li si vyzkoušet, jaké to je strávit dopoledne s dětmi v lese, můžete se přihlásit do kroužku Výletníček, který v zázemí školky pravidelně pořádá zřizovatel. Kroužek probíhá jednou týdně a je určený pro děti do 3 let s doprovodem. Více na <a href="https://www.lesnikavyl.cz/dalsiaktivity/volnocas">webu spolku</a>.</p>',
    created_at: '2021-02-23T20:22:31.766Z',
    updated_at: '2022-05-23T16:10:52.087Z',
  },
  {
    id: 22,
    Nazev: 'Tipy pro rodiče',
    Text: '<p>Už vám docházejí nápady? Nevadí!&nbsp;</p><p>Naši lektoři a pedagogové pro vás chystají pestrý nápadník básniček, her a tvoření do lesa i na doma. Během roku se budou s ročními obdobími měnit i naše tipy tak, abyste je mohli rovnou vyzkoušet.<br>Za pomoc děkujeme také kouzelníkovi se zvukem a obrazem <strong>Kamilu Šlapalovi</strong>, <a href="http://www.cafilm.cz/cz/">Craft Art Film</a>.</p><h3>Básničky a povídačky</h3><ul><li><a href="https://lesnikavyl.cz/files/jarni_basnicka.png">jarní básnička</a></li><li><a href="https://lesnikavyl.cz/files/Pampelina.pdf">Jak vařila Pampelína - jarní obrázkový příběh</a></li></ul><h3>Hry nejen do lesa</h3><ul><li><a href="https://lesnikavyl.cz/files/hry.png">3 hry (nejen) na jaro</a></li><li><a href="https://lesnikavyl.cz/files/pozorovani_prirody.png">pozorování přírody</a> (jaro)</li></ul><h3>Tvoření</h3><ul><li><a href="https://lesnikavyl.cz/files/krmitka.png">krmítka ze šišek</a></li></ul><h3>Do ouška</h3><ul><li><a href="https://lesnikavyl.cz/files/Tapy_Tap.mp3">Ťapy ťap</a></li><li><a href="/files/mami.mp3">Mami, proč jsi mi neřekla</a></li><li><a href="/files/snist.mp3">Co můžeš sníst dnes</a></li><li><a href="/files/tajne_heslo.mp3">Tajné heslo</a></li><li><a href="/files/kacatko.mp3">O ošklivém káčátku</a></li><li><a href="/files/tri_prasatka.mp3">O třech prasátkách</a></li></ul><h3>Svátky a tradice</h3><ul><li><a href="/files/morana.pdf">pálení Morany</a></li><li><a href="/files/jaro2.pdf">vítání jara</a></li></ul>',
    created_at: '2021-03-06T12:22:07.750Z',
    updated_at: '2021-04-14T06:31:57.733Z',
  },
  {
    id: 1,
    Nazev: 'O Stromíku 1',
    Text: '<p>Když v roce 2010 začal vznikat Stromík, rodil se ze snu několika maminek o školce v lese i na louce, o školce, která půjde ruku v ruce s přírodou. Jako jeden z prvních lesních klubů u nás začínal Stromík bez vlastního zázemí jen s několika nadšenými dětmi a mnoha touhami - učit se venku, vnímat a prožívat svět okolo nás všemi smysly.&nbsp;</p><p>Celých deset let si Stromík razí cestu vstříc ke stále kvalitnějšímu vzdělávání. Pravidelně prochází procesem certifikace Asociace lesních mateřských škol a splňuje <a href="https://www.lesnims.cz/lesni-ms/standardy-kvality.html">Standardy kvality</a>. Od školního roku 2021/22 je zapsán v rejstříku MŠMT jako Lesní mateřská škola Stromík. Nabízí plnohodnotné předškolní vzdělávání, předškoláci se nemusí na poslední rok loučit se svými kamarády a podporu dostanou i děti se speciálními potřebami. Paralelně funguje v areálu i její bratříček Lesní klub Jezerka.</p><p>Do školky s radostí vítáme také rodiče, kteří neodmyslitelně tvoří její společenství. Mají možnost zapojit se do příprav společných slavností, pomáhají nám spoluvytvářet prostředí a atmosféru školky.</p><p>Touha objevovat svět, radost z učení, respekt sám k sobě, k druhým lidem i přírodě je výbava, kterou chceme dávat našim dětem na jejich cestu životem.</p><p><i>Chcete-li sledovat, jak to u nás žije, přidejte si nás na </i><a href="https://www.facebook.com/Stromik"><i>Facebooku</i></a><i>.</i></p><p>Máte-li zájem o docházku do Stromíku, vyplňte nám prosím <a href="https://docs.google.com/forms/d/e/1FAIpQLSem7mOSVmkYT5X8xtyQfuS-oaN5-P0fGpVftl_6rFqq1S6rcg/viewform?usp=sf_link">Nezávazný dotazník</a> a my se vám ozveme.</p><p>Zřizovatelem LMŠ Stromík je spolek <a href="https://www.lesnikavyl.cz/">Kavyl z.s</a>.</p>',
    created_at: '2021-02-23T16:32:35.178Z',
    updated_at: '2022-02-16T09:49:07.525Z',
  },
  {
    id: 23,
    Nazev: 'Ceník 2',
    Text: '<h3><strong>Stravování&nbsp;</strong></h3><p>Obědy pro děti dovážíme ze školní jídelny ZŠ a MŠ Pozořice.</p><p>Cena dětské porce včetně dopravy je 58 Kč a není zahrnuta ve školkovném. Orientační cena stravování při celotýdenní docházce je 1100 Kč / měsíc.&nbsp;</p><p>Odhlášení oběda je možné do 12 hodin předchozího dne přes docházkový systém školky. Platba pozdě odhlášeného oběda je nevratná.</p>',
    created_at: '2021-03-11T16:59:53.539Z',
    updated_at: '2022-07-20T10:28:16.152Z',
  },
  {
    id: 24,
    Nazev: 'Nabídka práce',
    Text: '<p>Máte- li zájem o spolupráci nebo stáž, kontaktujte ředitelku LMŠ Stromík.&nbsp;</p><p><strong>Aktuálně:</strong><br>Rozšiřujeme tým průvodců na školní rok 2022/23, v případě zájmu pošlete svůj životopis a motivační dopis na <i>info@stromik.cz</i>. Podrobnosti najdete <a href="/aktualita/28">zde</a>.</p>',
    created_at: '2022-07-22T12:03:53.152Z',
    updated_at: '2022-07-22T12:29:02.792Z',
  },
  {
    id: 4,
    Nazev: 'Dokumenty',
    Text: '<p><a href="/files/SVP_2021.pdf">Školní vzdělávací program</a><br><a href="/files/skolni_rad_2021.pdf">Školní řád</a><br><a href="/files/provozni_rad_2021.pdf">Provozní řád</a><br><a href="/files/kriteria_prijeti_2022.pdf">Podmínky pro přijímání dětí</a><br><a href="/files/organizacni_rad_2022.pdf">Organizační řád</a></p><p><a href="/files/CSI_zprava_STR_2022.pdf">Inspekční zpráva ČŠI</a> - červen 2022</p><h3>Zápis</h3><p><a href="/files/zadost_Stromik.pdf">Žádost o přijetí</a><br><a href="/files/dotaznik_Stromik.pdf">Dotazník</a><br><a href="/files/evidence.pdf">Evidenční list</a><br><a href="/files/oznameni-iv.pdf">Oznámení o individuálním vzdělávání</a><br>&nbsp;</p><p><strong>Harmonogram školního roku LMŠ Stromík</strong><br><strong>2022-23</strong><br>1/9 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;začátek školního roku<br>28/9 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;státní svátek – zavřeno<br>28/10 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;státní svátek – zavřeno<br>17/11 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;státní svátek – zavřeno<br>23/12 – 1/1 &nbsp;vánoční prázdniny<br>7/4 – 10/4 &nbsp; &nbsp;Velikonoce – zavřeno<br>1/5 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; státní svátek - zavřeno<br>8/5 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; státní svátek - zavřeno<br>30/6 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; konec školního roku&nbsp;<br>1/7 – 31/8 &nbsp; &nbsp;prázdniny&nbsp;</p><p><br>&nbsp;</p>',
    created_at: '2021-02-23T20:14:26.709Z',
    updated_at: '2022-09-16T08:56:13.342Z',
  },
  {
    id: 11,
    Nazev: 'Tábory',
    Text: '<p>Letní příměstské tábory spolku Kavyl jsou určeny pro děti ve věku 3,5–7 let, které ještě nechodí do školy. Vybrané tábory jsou i pro školní děti (u termínu je uvedený věk). Jsou-li u jednoho termínu a místa uvedeny dva tábory, znamená to, že organizujeme dvě skupiny (předškolní a školní) se samostatným programem, tak abyste mohli přihlásit najednou sourozence různého věku.</p><p> Tábory se konají v zázemí Stromíku (v Pozořicích) a <a href="https://www.lesnimarianka.cz/kontakt">Mariánky (v Líšni)</a> a v okolních lesích. Provozní doba tábora je vždy od pondělí do pátku od 8 do 16 h.</p><h3>Tábory 2023</h3><p><i>Příměstské tábory se budou konat v následujících termínech. <br/><br/> Brno-Líšeň (Mariánka)<br/> 10. - 14. 7. (3,5 – 7 let) Kouzelný les a jeho obyvatelé<br/> 17. - 21. 7. (5 – 8 let) Bylo, nebylo a co bude dál? <br/> 21. - 25. 8. (3,5 – 7 let) Dobrodružství v Čarolese<br/><br/>Pozořice (Stromík) <br/>10. - 14. 7. (1. – 3. třída) Hmyzí detektivové<br/>24. - 28. 7. (3,5 – 7 let a 7–10 let) Indiánskou stezkou<br/> 7. - 11. 8. (5 – 10 let) Mauglího dobrodružství - obsazeno<br/>14. - 18. 8. (3,5 – 7 let) Byla jednou jedna nota<br/> 21. - 25. 8. (3,5 – 7 let) Kouzelný les<br/><br/>Cena tábora je 2 500 Kč.<br/><br/>Přihlašovat můžete děti prostřednictvím <a href="https://forms.gle/raR2sCa3uFJmLZJR6">ONLINE PŘIHLÁŠKY</a>.<br/><br/>Zajímají-li vás podrobněji jednotlivá témata táborů, podívejte se na <a href="https://www.lesnikavyl.cz/files/tabory_anotace_2023.png">anotace</a>.<br/><br/>Těšíme se v létě na viděnou!</i>',
    created_at: '2021-02-23T20:26:14.930Z',
    updated_at: '2022-09-16T08:57:42.799Z',
  },
  {
    id: 12,
    Nazev: 'Kontakt2',
    Text: '<h3>Lesní mateřská škola Stromík</h3><p>školská právnická osoba<br>Sídlo: Hostěnická 626, 664 07 Pozořice<br>IČ: 09 823 395<br>Datová schránka:&nbsp;&nbsp;y83gybs<br>Číslo účtu:&nbsp;2902035711/2010<br>E-mail: <a href="mailto:info@stromik.cz">info@stromik.cz</a><br><a href="https://www.facebook.com/Stromik">facebook LMŠ Stromík</a></p><h3>Pro rodiče:</h3><p>Jindra Klemešová<br>tel: 604 523 160<br>koordinator@stromik.cz</p><h3>Ředitelka:</h3><p>Mgr. Klára Krchňavá<br>tel.: 777 145 343<br>e-mail: klara.krchnava@stromik.cz</p><h3>Zřizovatel:</h3><p>Kavyl z.s.<br>Hostěnická 626, 664 07 Pozořice<br>IČ: 229 09 320<br><a href="https://www.lesnikavyl.cz/">lesnikavyl.cz</a></p><h3>Pracovní příležitosti</h3><p>Máte- li zájem o spolupráci nebo stáž, kontaktujte ředitelku LMŠ Stromík.&nbsp;</p>',
    created_at: '2021-02-23T20:26:53.067Z',
    updated_at: '2022-09-28T16:22:59.985Z',
  },
];
